file:///ta_account.wsdl
<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:CorticonService" xmlns:cc="urn:Corticon" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="urn:CorticonService">
    <types>
        <xsd:schema xmlns:tns="urn:Corticon" targetNamespace="urn:Corticon" elementFormDefault="qualified">
            <xsd:element name="CorticonRequest" type="tns:CorticonRequest" />
            <xsd:element name="CorticonResponse" type="tns:CorticonResponse" />
            <xsd:complexType name="CorticonRequest">
                <xsd:sequence>
                    <xsd:element name="WorkDocuments" type="tns:WorkDocuments" />
                </xsd:sequence>
                <xsd:attribute name="decisionServiceName" use="required" type="xsd:string" />
                <xsd:attribute name="decisionServiceTargetVersion" use="optional" type="xsd:nonNegativeInteger" />
                <xsd:attribute name="decisionServiceEffectiveTimestamp" use="optional" type="xsd:dateTime" />
                <xsd:attribute name="usage" use="optional" type="xsd:string" />
            </xsd:complexType>
            <xsd:complexType name="CorticonResponse">
                <xsd:sequence>
                    <xsd:element name="WorkDocuments" type="tns:WorkDocuments" />
                    <xsd:element name="Messages" type="tns:Messages" />
                </xsd:sequence>
                <xsd:attribute name="decisionServiceName" use="required" type="xsd:string" />
                <xsd:attribute name="decisionServiceTargetVersion" use="optional" type="xsd:nonNegativeInteger" />
                <xsd:attribute name="decisionServiceEffectiveTimestamp" use="optional" type="xsd:dateTime" />
                <xsd:attribute name="usage" use="optional" type="xsd:string" />
            </xsd:complexType>
            <xsd:complexType name="WorkDocuments">
                <xsd:choice maxOccurs="unbounded">
                    <xsd:element name="Account" type="tns:Account" />
                </xsd:choice>
                <xsd:attribute name="messageType" fixed="HIER" use="required" type="xsd:string" />
            </xsd:complexType>
            <xsd:complexType name="Messages">
                <xsd:sequence>
                    <xsd:element name="Message" type="tns:Message" minOccurs="0" maxOccurs="unbounded" />
                </xsd:sequence>
                <xsd:attribute name="version" type="xsd:string" />
            </xsd:complexType>
            <xsd:complexType name="Message">
                <xsd:sequence>
                    <xsd:element name="severity">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:string">
                                <xsd:enumeration value="Info" />
                                <xsd:enumeration value="Warning" />
                                <xsd:enumeration value="Violation" />
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="text" type="xsd:string" />
                    <xsd:element name="entityReference">
                        <xsd:complexType>
                            <xsd:attribute name="href" type="xsd:anyURI" />
                        </xsd:complexType>
                    </xsd:element>
                </xsd:sequence>
            </xsd:complexType>
            <xsd:complexType name="Account">
                <xsd:sequence>
                    <xsd:element name="accountSegment" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="amo" type="xsd:long" nillable="true" minOccurs="0" />
                    <xsd:element name="country" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="industry" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="organizationName" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="postalCode" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="recordType" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="sfdcAccountId" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="stateProvince" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="accountTeamMember" type="tns:AccountTeamMember" minOccurs="0" maxOccurs="unbounded" />
                </xsd:sequence>
                <xsd:attribute name="id" type="xsd:string" use="optional" />
                <xsd:attribute name="href" type="xsd:anyURI" use="optional" />
            </xsd:complexType>
            <xsd:complexType name="AccountTeamMember">
                <xsd:sequence>
                    <xsd:element name="accountMgrType" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="adobeRole" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="named" type="xsd:boolean" nillable="true" minOccurs="0" />
                    <xsd:element name="outlookProductGroup" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="ruleName" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="taOverlayCompositeId" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="taSFDCGuid" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="teamDesignation" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="userId" type="xsd:string" nillable="true" minOccurs="0" />
                    <xsd:element name="userName" type="xsd:string" nillable="true" minOccurs="0" />
                </xsd:sequence>
                <xsd:attribute name="id" type="xsd:string" use="optional" />
                <xsd:attribute name="href" type="xsd:anyURI" use="optional" />
            </xsd:complexType>
        </xsd:schema>
    </types>
    <message name="CorticonRequestIn">
        <part name="parameters" element="cc:CorticonRequest" />
    </message>
    <message name="CorticonResponseOut">
        <part name="parameters" element="cc:CorticonResponse" />
    </message>
    <portType name="TADecisionServiceSoap">
        <operation name="processRequest">
            <input message="tns:CorticonRequestIn" />
            <output message="tns:CorticonResponseOut" />
        </operation>
    </portType>
    <binding name="TADecisionServiceSoap" type="tns:TADecisionServiceSoap">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document" />
        <operation name="processRequest">
            <soap:operation soapAction="urn:Corticon" style="document" />
            <input>
                <soap:body use="literal" namespace="urn:Corticon" />
            </input>
            <output>
                <soap:body use="literal" namespace="urn:Corticon" />
            </output>
        </operation>
    </binding>
    <service name="TADecisionService">
        <documentation>InsertDecisionServiceDescription</documentation>
        <port name="TADecisionServiceSoap" binding="tns:TADecisionServiceSoap">
            <soap:address location="https://rules-stg.corp.adobe.com/axis//services/Corticon" />
        </port>
    </service>
</definitions>