//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommonGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CommonGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}PymtType" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ReversalInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TxnType" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}LocalDateTime" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TrnmsnDateTime" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}STAN" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}RefNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OrderNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TPPID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TPPID2" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TermID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}MerchID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}AltMerchID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}MerchCatCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}POSEntryMode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}POSCondCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TermCatCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TermEntryCapablt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TxnAmt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TxnCrncy" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TermLocInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}CardCaptCap" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ProgramID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}GroupID" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CommonGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "pymtType",
    "reversalInd",
    "txnType",
    "localDateTime",
    "trnmsnDateTime",
    "stan",
    "refNum",
    "orderNum",
    "tppid",
    "tppid2",
    "termID",
    "merchID",
    "altMerchID",
    "merchCatCode",
    "posEntryMode",
    "posCondCode",
    "termCatCode",
    "termEntryCapablt",
    "txnAmt",
    "txnCrncy",
    "termLocInd",
    "cardCaptCap",
    "programID",
    "groupID"
})
public class CommonGrp {

    @XmlElement(name = "PymtType")
    protected PymtTypeType pymtType;
    @XmlElement(name = "ReversalInd")
    protected ReversalIndType reversalInd;
    @XmlElement(name = "TxnType")
    protected TxnTypeType txnType;
    @XmlElement(name = "LocalDateTime")
    protected String localDateTime;
    @XmlElement(name = "TrnmsnDateTime")
    protected String trnmsnDateTime;
    @XmlElement(name = "STAN")
    protected String stan;
    @XmlElement(name = "RefNum")
    protected String refNum;
    @XmlElement(name = "OrderNum")
    protected String orderNum;
    @XmlElement(name = "TPPID")
    protected String tppid;
    @XmlElement(name = "TPPID2")
    protected String tppid2;
    @XmlElement(name = "TermID")
    protected String termID;
    @XmlElement(name = "MerchID")
    protected String merchID;
    @XmlElement(name = "AltMerchID")
    protected String altMerchID;
    @XmlElement(name = "MerchCatCode")
    protected String merchCatCode;
    @XmlElement(name = "POSEntryMode")
    protected String posEntryMode;
    @XmlElement(name = "POSCondCode")
    protected String posCondCode;
    @XmlElement(name = "TermCatCode")
    protected String termCatCode;
    @XmlElement(name = "TermEntryCapablt")
    protected String termEntryCapablt;
    @XmlElement(name = "TxnAmt")
    protected String txnAmt;
    @XmlElement(name = "TxnCrncy")
    protected String txnCrncy;
    @XmlElement(name = "TermLocInd")
    protected String termLocInd;
    @XmlElement(name = "CardCaptCap")
    protected String cardCaptCap;
    @XmlElement(name = "ProgramID")
    protected String programID;
    @XmlElement(name = "GroupID")
    protected String groupID;

    /**
     * Gets the value of the pymtType property.
     * 
     * @return
     *     possible object is
     *     {@link PymtTypeType }
     *     
     */
    public PymtTypeType getPymtType() {
        return pymtType;
    }

    /**
     * Sets the value of the pymtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PymtTypeType }
     *     
     */
    public void setPymtType(PymtTypeType value) {
        this.pymtType = value;
    }

    /**
     * Gets the value of the reversalInd property.
     * 
     * @return
     *     possible object is
     *     {@link ReversalIndType }
     *     
     */
    public ReversalIndType getReversalInd() {
        return reversalInd;
    }

    /**
     * Sets the value of the reversalInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReversalIndType }
     *     
     */
    public void setReversalInd(ReversalIndType value) {
        this.reversalInd = value;
    }

    /**
     * Gets the value of the txnType property.
     * 
     * @return
     *     possible object is
     *     {@link TxnTypeType }
     *     
     */
    public TxnTypeType getTxnType() {
        return txnType;
    }

    /**
     * Sets the value of the txnType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TxnTypeType }
     *     
     */
    public void setTxnType(TxnTypeType value) {
        this.txnType = value;
    }

    /**
     * Gets the value of the localDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalDateTime() {
        return localDateTime;
    }

    /**
     * Sets the value of the localDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalDateTime(String value) {
        this.localDateTime = value;
    }

    /**
     * Gets the value of the trnmsnDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrnmsnDateTime() {
        return trnmsnDateTime;
    }

    /**
     * Sets the value of the trnmsnDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrnmsnDateTime(String value) {
        this.trnmsnDateTime = value;
    }

    /**
     * Gets the value of the stan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTAN() {
        return stan;
    }

    /**
     * Sets the value of the stan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTAN(String value) {
        this.stan = value;
    }

    /**
     * Gets the value of the refNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefNum() {
        return refNum;
    }

    /**
     * Sets the value of the refNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefNum(String value) {
        this.refNum = value;
    }

    /**
     * Gets the value of the orderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * Sets the value of the orderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderNum(String value) {
        this.orderNum = value;
    }

    /**
     * Gets the value of the tppid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTPPID() {
        return tppid;
    }

    /**
     * Sets the value of the tppid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTPPID(String value) {
        this.tppid = value;
    }

    /**
     * Gets the value of the tppid2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTPPID2() {
        return tppid2;
    }

    /**
     * Sets the value of the tppid2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTPPID2(String value) {
        this.tppid2 = value;
    }

    /**
     * Gets the value of the termID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermID() {
        return termID;
    }

    /**
     * Sets the value of the termID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermID(String value) {
        this.termID = value;
    }

    /**
     * Gets the value of the merchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchID() {
        return merchID;
    }

    /**
     * Sets the value of the merchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchID(String value) {
        this.merchID = value;
    }

    /**
     * Gets the value of the altMerchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAltMerchID() {
        return altMerchID;
    }

    /**
     * Sets the value of the altMerchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAltMerchID(String value) {
        this.altMerchID = value;
    }

    /**
     * Gets the value of the merchCatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchCatCode() {
        return merchCatCode;
    }

    /**
     * Sets the value of the merchCatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchCatCode(String value) {
        this.merchCatCode = value;
    }

    /**
     * Gets the value of the posEntryMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSEntryMode() {
        return posEntryMode;
    }

    /**
     * Sets the value of the posEntryMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSEntryMode(String value) {
        this.posEntryMode = value;
    }

    /**
     * Gets the value of the posCondCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSCondCode() {
        return posCondCode;
    }

    /**
     * Sets the value of the posCondCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSCondCode(String value) {
        this.posCondCode = value;
    }

    /**
     * Gets the value of the termCatCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermCatCode() {
        return termCatCode;
    }

    /**
     * Sets the value of the termCatCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermCatCode(String value) {
        this.termCatCode = value;
    }

    /**
     * Gets the value of the termEntryCapablt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermEntryCapablt() {
        return termEntryCapablt;
    }

    /**
     * Sets the value of the termEntryCapablt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermEntryCapablt(String value) {
        this.termEntryCapablt = value;
    }

    /**
     * Gets the value of the txnAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnAmt() {
        return txnAmt;
    }

    /**
     * Sets the value of the txnAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnAmt(String value) {
        this.txnAmt = value;
    }

    /**
     * Gets the value of the txnCrncy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxnCrncy() {
        return txnCrncy;
    }

    /**
     * Sets the value of the txnCrncy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxnCrncy(String value) {
        this.txnCrncy = value;
    }

    /**
     * Gets the value of the termLocInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermLocInd() {
        return termLocInd;
    }

    /**
     * Sets the value of the termLocInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermLocInd(String value) {
        this.termLocInd = value;
    }

    /**
     * Gets the value of the cardCaptCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardCaptCap() {
        return cardCaptCap;
    }

    /**
     * Sets the value of the cardCaptCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardCaptCap(String value) {
        this.cardCaptCap = value;
    }

    /**
     * Gets the value of the programID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgramID() {
        return programID;
    }

    /**
     * Sets the value of the programID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgramID(String value) {
        this.programID = value;
    }

    /**
     * Gets the value of the groupID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupID() {
        return groupID;
    }

    /**
     * Sets the value of the groupID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupID(String value) {
        this.groupID = value;
    }

}
