//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EBTTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EBTTypeType">
 *   &lt;restriction base="{com/firstdata/Merchant/gmfV1.1}Max7Text">
 *     &lt;enumeration value="EBTFood"/>
 *     &lt;enumeration value="EBTCash"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EBTTypeType", namespace = "com/firstdata/Merchant/gmfV1.1")
@XmlEnum
public enum EBTTypeType {

    @XmlEnumValue("EBTFood")
    EBT_FOOD("EBTFood"),
    @XmlEnumValue("EBTCash")
    EBT_CASH("EBTCash");
    private final String value;

    EBTTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EBTTypeType fromValue(String v) {
        for (EBTTypeType c: EBTTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
