//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EcommGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EcommGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}EcommTxnInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}CustSvcPhoneNumber" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}EcommURL" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EcommGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "ecommTxnInd",
    "custSvcPhoneNumber",
    "ecommURL"
})
public class EcommGrp {

    @XmlElement(name = "EcommTxnInd")
    protected String ecommTxnInd;
    @XmlElement(name = "CustSvcPhoneNumber")
    protected String custSvcPhoneNumber;
    @XmlElement(name = "EcommURL")
    protected String ecommURL;

    /**
     * Gets the value of the ecommTxnInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcommTxnInd() {
        return ecommTxnInd;
    }

    /**
     * Sets the value of the ecommTxnInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcommTxnInd(String value) {
        this.ecommTxnInd = value;
    }

    /**
     * Gets the value of the custSvcPhoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustSvcPhoneNumber() {
        return custSvcPhoneNumber;
    }

    /**
     * Sets the value of the custSvcPhoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustSvcPhoneNumber(String value) {
        this.custSvcPhoneNumber = value;
    }

    /**
     * Gets the value of the ecommURL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEcommURL() {
        return ecommURL;
    }

    /**
     * Sets the value of the ecommURL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEcommURL(String value) {
        this.ecommURL = value;
    }

}
