//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.toolkit.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TeleCheckECAGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TeleCheckECAGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ChkType" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ChkClrkID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ChkProdCd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}DnlRecNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ChkNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ChkPhnNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ChkTrcID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ChkBCN" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TeleCheckECAGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "chkType",
    "chkClrkID",
    "chkProdCd",
    "dnlRecNum",
    "chkNum",
    "chkPhnNum",
    "chkTrcID",
    "chkBCN"
})
public class TeleCheckECAGrp {

    @XmlElement(name = "ChkType")
    protected ChkTypeType chkType;
    @XmlElement(name = "ChkClrkID")
    protected String chkClrkID;
    @XmlElement(name = "ChkProdCd")
    protected String chkProdCd;
    @XmlElement(name = "DnlRecNum")
    protected String dnlRecNum;
    @XmlElement(name = "ChkNum")
    protected String chkNum;
    @XmlElement(name = "ChkPhnNum")
    protected String chkPhnNum;
    @XmlElement(name = "ChkTrcID")
    protected String chkTrcID;
    @XmlElement(name = "ChkBCN")
    protected String chkBCN;

    /**
     * Gets the value of the chkType property.
     * 
     * @return
     *     possible object is
     *     {@link ChkTypeType }
     *     
     */
    public ChkTypeType getChkType() {
        return chkType;
    }

    /**
     * Sets the value of the chkType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChkTypeType }
     *     
     */
    public void setChkType(ChkTypeType value) {
        this.chkType = value;
    }

    /**
     * Gets the value of the chkClrkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChkClrkID() {
        return chkClrkID;
    }

    /**
     * Sets the value of the chkClrkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChkClrkID(String value) {
        this.chkClrkID = value;
    }

    /**
     * Gets the value of the chkProdCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChkProdCd() {
        return chkProdCd;
    }

    /**
     * Sets the value of the chkProdCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChkProdCd(String value) {
        this.chkProdCd = value;
    }

    /**
     * Gets the value of the dnlRecNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDnlRecNum() {
        return dnlRecNum;
    }

    /**
     * Sets the value of the dnlRecNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDnlRecNum(String value) {
        this.dnlRecNum = value;
    }

    /**
     * Gets the value of the chkNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChkNum() {
        return chkNum;
    }

    /**
     * Sets the value of the chkNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChkNum(String value) {
        this.chkNum = value;
    }

    /**
     * Gets the value of the chkPhnNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChkPhnNum() {
        return chkPhnNum;
    }

    /**
     * Sets the value of the chkPhnNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChkPhnNum(String value) {
        this.chkPhnNum = value;
    }

    /**
     * Gets the value of the chkTrcID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChkTrcID() {
        return chkTrcID;
    }

    /**
     * Sets the value of the chkTrcID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChkTrcID(String value) {
        this.chkTrcID = value;
    }

    /**
     * Gets the value of the chkBCN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChkBCN() {
        return chkBCN;
    }

    /**
     * Sets the value of the chkBCN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChkBCN(String value) {
        this.chkBCN = value;
    }

}
