/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlType(name = "AddAmtTypeType", namespace = "com/firstdata/Merchant/gmfV2.08")
@XmlEnum
public enum AddAmtTypeType {

    @XmlEnumValue("Cashback")
    CASHBACK("Cashback"), @XmlEnumValue("Surchrg")
    SURCHRG("Surchrg"), @XmlEnumValue("FirstAuthAmt")
    FIRST_AUTH_AMT("FirstAuthAmt"), @XmlEnumValue("PreAuthAmt")
    PRE_AUTH_AMT("PreAuthAmt"), @XmlEnumValue("TotalAuthAmt")
    TOTAL_AUTH_AMT("TotalAuthAmt"), @XmlEnumValue("Tax")
    TAX("Tax"), @XmlEnumValue("BegBal")
    BEG_BAL("BegBal"), @XmlEnumValue("EndingBal")
    ENDING_BAL("EndingBal"), @XmlEnumValue("AvailBal")
    AVAIL_BAL("AvailBal"), @XmlEnumValue("LedgerBal")
    LEDGER_BAL("LedgerBal"), @XmlEnumValue("HoldBal")
    HOLD_BAL("HoldBal"), @XmlEnumValue("OrigReqAmt")
    ORIG_REQ_AMT("OrigReqAmt"), @XmlEnumValue("OpenToBuy")
    OPEN_TO_BUY("OpenToBuy");
    private final String value;

    AddAmtTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AddAmtTypeType fromValue(String v) {
        for (AddAmtTypeType c : AddAmtTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
