//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AddtlAmtGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddtlAmtGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}AddAmt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}AddAmtCrncy" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}AddAmtType" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}AddAmtAcctType" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}HoldInfo" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}PartAuthrztnApprvlCapablt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddtlAmtGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "addAmt",
    "addAmtCrncy",
    "addAmtType",
    "addAmtAcctType",
    "holdInfo",
    "partAuthrztnApprvlCapablt"
})
public class AddtlAmtGrp {

    @XmlElement(name = "AddAmt")
    protected String addAmt;
    @XmlElement(name = "AddAmtCrncy")
    protected String addAmtCrncy;
    @XmlElement(name = "AddAmtType")
    protected String addAmtType;
    @XmlElement(name = "AddAmtAcctType")
    protected AddAmtAcctTypeType addAmtAcctType;
    @XmlElement(name = "HoldInfo")
    protected String holdInfo;
    @XmlElement(name = "PartAuthrztnApprvlCapablt")
    protected String partAuthrztnApprvlCapablt;

    /**
     * Gets the value of the addAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddAmt() {
        return addAmt;
    }

    /**
     * Sets the value of the addAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddAmt(String value) {
        this.addAmt = value;
    }

    /**
     * Gets the value of the addAmtCrncy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddAmtCrncy() {
        return addAmtCrncy;
    }

    /**
     * Sets the value of the addAmtCrncy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddAmtCrncy(String value) {
        this.addAmtCrncy = value;
    }

    /**
     * Gets the value of the addAmtType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddAmtType() {
        return addAmtType;
    }

    /**
     * Sets the value of the addAmtType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddAmtType(String value) {
        this.addAmtType = value;
    }

    /**
     * Gets the value of the addAmtAcctType property.
     * 
     * @return
     *     possible object is
     *     {@link AddAmtAcctTypeType }
     *     
     */
    public AddAmtAcctTypeType getAddAmtAcctType() {
        return addAmtAcctType;
    }

    /**
     * Sets the value of the addAmtAcctType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddAmtAcctTypeType }
     *     
     */
    public void setAddAmtAcctType(AddAmtAcctTypeType value) {
        this.addAmtAcctType = value;
    }

    /**
     * Gets the value of the holdInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHoldInfo() {
        return holdInfo;
    }

    /**
     * Sets the value of the holdInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHoldInfo(String value) {
        this.holdInfo = value;
    }

    /**
     * Gets the value of the partAuthrztnApprvlCapablt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartAuthrztnApprvlCapablt() {
        return partAuthrztnApprvlCapablt;
    }

    /**
     * Sets the value of the partAuthrztnApprvlCapablt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartAuthrztnApprvlCapablt(String value) {
        this.partAuthrztnApprvlCapablt = value;
    }

}
