/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = { "acctNum",
        "cardActivDate", "cardExpiryDate", "track1Data", "track2Data", "cardType", "avsResultCode",
        "ccvInd", "ccvData", "ccvResultCode" })
public class CardGrp {

    @XmlElement(name = "AcctNum", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String acctNum;
    @XmlElement(name = "CardActivDate", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String cardActivDate;
    @XmlElement(name = "CardExpiryDate", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String cardExpiryDate;
    @XmlElement(name = "Track1Data", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String track1Data;
    @XmlElement(name = "Track2Data", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String track2Data;
    @XmlElement(name = "CardType", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CardTypeType cardType;
    @XmlElement(name = "AVSResultCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected AVSResultCodeType avsResultCode;
    @XmlElement(name = "CCVInd", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CCVIndType ccvInd;
    @XmlElement(name = "CCVData", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String ccvData;
    @XmlElement(name = "CCVResultCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CCVResultCodeType ccvResultCode;

    public String getAcctNum() {
        return acctNum;
    }

    public void setAcctNum(String value) {
        this.acctNum = value;
    }

    public String getCardActivDate() {
        return cardActivDate;
    }

    public void setCardActivDate(String value) {
        this.cardActivDate = value;
    }

    public String getCardExpiryDate() {
        return cardExpiryDate;
    }

    public void setCardExpiryDate(String value) {
        this.cardExpiryDate = value;
    }

    public String getTrack1Data() {
        return track1Data;
    }

    public void setTrack1Data(String value) {
        this.track1Data = value;
    }

    public String getTrack2Data() {
        return track2Data;
    }

    public void setTrack2Data(String value) {
        this.track2Data = value;
    }

    public CardTypeType getCardType() {
        return cardType;
    }

    public void setCardType(CardTypeType value) {
        this.cardType = value;
    }

    public AVSResultCodeType getAVSResultCode() {
        return avsResultCode;
    }

    public void setAVSResultCode(AVSResultCodeType value) {
        this.avsResultCode = value;
    }

    public CCVIndType getCCVInd() {
        return ccvInd;
    }

    public void setCCVInd(CCVIndType value) {
        this.ccvInd = value;
    }

    public String getCCVData() {
        return ccvData;
    }

    public void setCCVData(String value) {
        this.ccvData = value;
    }

    public CCVResultCodeType getCCVResultCode() {
        return ccvResultCode;
    }

    public void setCCVResultCode(CCVResultCodeType value) {
        this.ccvResultCode = value;
    }

}
