/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditRequestDetails", namespace = "com/firstdata/Merchant/gmfV2.08",
        propOrder = { "commonGrp", "billPayGrp", "altMerchNameAndAddrGrp", "cardGrp",
                "addtlAmtGrp", "emvGrp", "taGrp", "offerGrp", "ecommGrp", "secrTxnGrp", "visaGrp",
                "mcGrp", "dsGrp", "amexGrp", "purchCardlvl2Grp", "custInfoGrp", "orderGrp",
                "origAuthGrp", "prodCodeGrp", "prodCodeDetGrp" })
public class CreditRequestDetails {

    @XmlElement(name = "CommonGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CommonGrp commonGrp;
    @XmlElement(name = "BillPayGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected BillPayGrp billPayGrp;
    @XmlElement(name = "AltMerchNameAndAddrGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected AltMerchNameAndAddrGrp altMerchNameAndAddrGrp;
    @XmlElement(name = "CardGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CardGrp cardGrp;
    @XmlElement(name = "AddtlAmtGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected List<AddtlAmtGrp> addtlAmtGrp;
    @XmlElement(name = "EMVGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected EMVGrp emvGrp;
    @XmlElement(name = "TAGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected TAGrp taGrp;
    @XmlElement(name = "OfferGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected OfferGrp offerGrp;
    @XmlElement(name = "EcommGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected EcommGrp ecommGrp;
    @XmlElement(name = "SecrTxnGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected SecrTxnGrp secrTxnGrp;
    @XmlElement(name = "VisaGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected VisaGrp visaGrp;
    @XmlElement(name = "MCGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected MCGrp mcGrp;
    @XmlElement(name = "DSGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected DSGrp dsGrp;
    @XmlElement(name = "AmexGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected AmexGrp amexGrp;
    @XmlElement(name = "PurchCardlvl2Grp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected PurchCardlvl2Grp purchCardlvl2Grp;
    @XmlElement(name = "CustInfoGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CustInfoGrp custInfoGrp;
    @XmlElement(name = "OrderGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected OrderGrp orderGrp;
    @XmlElement(name = "OrigAuthGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected OrigAuthGrp origAuthGrp;
    @XmlElement(name = "ProdCodeGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected ProdCodeGrp prodCodeGrp;
    @XmlElement(name = "ProdCodeDetGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected List<ProdCodeDetGrp> prodCodeDetGrp;

    public CommonGrp getCommonGrp() {
        return commonGrp;
    }

    public void setCommonGrp(CommonGrp value) {
        this.commonGrp = value;
    }

    public BillPayGrp getBillPayGrp() {
        return billPayGrp;
    }

    public void setBillPayGrp(BillPayGrp value) {
        this.billPayGrp = value;
    }

    public AltMerchNameAndAddrGrp getAltMerchNameAndAddrGrp() {
        return altMerchNameAndAddrGrp;
    }

    public void setAltMerchNameAndAddrGrp(AltMerchNameAndAddrGrp value) {
        this.altMerchNameAndAddrGrp = value;
    }

    public CardGrp getCardGrp() {
        return cardGrp;
    }

    public void setCardGrp(CardGrp value) {
        this.cardGrp = value;
    }

    public List<AddtlAmtGrp> getAddtlAmtGrp() {
        if (addtlAmtGrp == null) {
            addtlAmtGrp = new ArrayList<AddtlAmtGrp>();
        }
        return this.addtlAmtGrp;
    }

    public EMVGrp getEMVGrp() {
        return emvGrp;
    }

    public void setEMVGrp(EMVGrp value) {
        this.emvGrp = value;
    }

    public TAGrp getTAGrp() {
        return taGrp;
    }

    public void setTAGrp(TAGrp value) {
        this.taGrp = value;
    }

    public OfferGrp getOfferGrp() {
        return offerGrp;
    }

    public void setOfferGrp(OfferGrp value) {
        this.offerGrp = value;
    }

    public EcommGrp getEcommGrp() {
        return ecommGrp;
    }

    public void setEcommGrp(EcommGrp value) {
        this.ecommGrp = value;
    }

    public SecrTxnGrp getSecrTxnGrp() {
        return secrTxnGrp;
    }

    public void setSecrTxnGrp(SecrTxnGrp value) {
        this.secrTxnGrp = value;
    }

    public VisaGrp getVisaGrp() {
        return visaGrp;
    }

    public void setVisaGrp(VisaGrp value) {
        this.visaGrp = value;
    }

    public MCGrp getMCGrp() {
        return mcGrp;
    }

    public void setMCGrp(MCGrp value) {
        this.mcGrp = value;
    }

    public DSGrp getDSGrp() {
        return dsGrp;
    }

    public void setDSGrp(DSGrp value) {
        this.dsGrp = value;
    }

    public AmexGrp getAmexGrp() {
        return amexGrp;
    }

    public void setAmexGrp(AmexGrp value) {
        this.amexGrp = value;
    }

    public PurchCardlvl2Grp getPurchCardlvl2Grp() {
        return purchCardlvl2Grp;
    }

    public void setPurchCardlvl2Grp(PurchCardlvl2Grp value) {
        this.purchCardlvl2Grp = value;
    }

    public CustInfoGrp getCustInfoGrp() {
        return custInfoGrp;
    }

    public void setCustInfoGrp(CustInfoGrp value) {
        this.custInfoGrp = value;
    }

    public OrderGrp getOrderGrp() {
        return orderGrp;
    }

    public void setOrderGrp(OrderGrp value) {
        this.orderGrp = value;
    }

    public OrigAuthGrp getOrigAuthGrp() {
        return origAuthGrp;
    }

    public void setOrigAuthGrp(OrigAuthGrp value) {
        this.origAuthGrp = value;
    }

    public ProdCodeGrp getProdCodeGrp() {
        return prodCodeGrp;
    }

    public void setProdCodeGrp(ProdCodeGrp value) {
        this.prodCodeGrp = value;
    }

    public List<ProdCodeDetGrp> getProdCodeDetGrp() {
        if (prodCodeDetGrp == null) {
            prodCodeDetGrp = new ArrayList<ProdCodeDetGrp>();
        }
        return this.prodCodeDetGrp;
    }

}
