//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.proxy;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CreditResponseDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreditResponseDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CommonGrp" type="{com/firstdata/Merchant/gmfV1.1}CommonGrp" minOccurs="0"/>
 *         &lt;element name="BillPayGrp" type="{com/firstdata/Merchant/gmfV1.1}BillPayGrp" minOccurs="0"/>
 *         &lt;element name="CardGrp" type="{com/firstdata/Merchant/gmfV1.1}CardGrp" minOccurs="0"/>
 *         &lt;element name="AddtlAmtGrp" type="{com/firstdata/Merchant/gmfV1.1}AddtlAmtGrp" maxOccurs="6" minOccurs="0"/>
 *         &lt;element name="EMVGrp" type="{com/firstdata/Merchant/gmfV1.1}EMVGrp" minOccurs="0"/>
 *         &lt;element name="TAGrp" type="{com/firstdata/Merchant/gmfV1.1}TAGrp" minOccurs="0"/>
 *         &lt;element name="OfferGrp" type="{com/firstdata/Merchant/gmfV1.1}OfferGrp" minOccurs="0"/>
 *         &lt;element name="EcommGrp" type="{com/firstdata/Merchant/gmfV1.1}EcommGrp" minOccurs="0"/>
 *         &lt;element name="SecrTxnGrp" type="{com/firstdata/Merchant/gmfV1.1}SecrTxnGrp" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="VisaGrp" type="{com/firstdata/Merchant/gmfV1.1}VisaGrp" minOccurs="0"/>
 *           &lt;element name="MCGrp" type="{com/firstdata/Merchant/gmfV1.1}MCGrp" minOccurs="0"/>
 *           &lt;element name="DSGrp" type="{com/firstdata/Merchant/gmfV1.1}DSGrp" minOccurs="0"/>
 *           &lt;element name="AmexGrp" type="{com/firstdata/Merchant/gmfV1.1}AmexGrp" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="RespGrp" type="{com/firstdata/Merchant/gmfV1.1}RespGrp" minOccurs="0"/>
 *         &lt;element name="OrigAuthGrp" type="{com/firstdata/Merchant/gmfV1.1}OrigAuthGrp" minOccurs="0"/>
 *         &lt;element name="FraudMitGrp" type="{com/firstdata/Merchant/gmfV1.1}FraudMitGrp" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreditResponseDetails", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "commonGrp",
    "billPayGrp",
    "cardGrp",
    "addtlAmtGrp",
    "emvGrp",
    "taGrp",
    "offerGrp",
    "ecommGrp",
    "secrTxnGrp",
    "visaGrp",
    "mcGrp",
    "dsGrp",
    "amexGrp",
    "respGrp",
    "origAuthGrp",
    "fraudMitGrp"
})
public class CreditResponseDetails {

    @XmlElement(name = "CommonGrp")
    protected CommonGrp commonGrp;
    @XmlElement(name = "BillPayGrp")
    protected BillPayGrp billPayGrp;
    @XmlElement(name = "CardGrp")
    protected CardGrp cardGrp;
    @XmlElement(name = "AddtlAmtGrp")
    protected List<AddtlAmtGrp> addtlAmtGrp;
    @XmlElement(name = "EMVGrp")
    protected EMVGrp emvGrp;
    @XmlElement(name = "TAGrp")
    protected TAGrp taGrp;
    @XmlElement(name = "OfferGrp")
    protected OfferGrp offerGrp;
    @XmlElement(name = "EcommGrp")
    protected EcommGrp ecommGrp;
    @XmlElement(name = "SecrTxnGrp")
    protected SecrTxnGrp secrTxnGrp;
    @XmlElement(name = "VisaGrp")
    protected VisaGrp visaGrp;
    @XmlElement(name = "MCGrp")
    protected MCGrp mcGrp;
    @XmlElement(name = "DSGrp")
    protected DSGrp dsGrp;
    @XmlElement(name = "AmexGrp")
    protected AmexGrp amexGrp;
    @XmlElement(name = "RespGrp")
    protected RespGrp respGrp;
    @XmlElement(name = "OrigAuthGrp")
    protected OrigAuthGrp origAuthGrp;
    @XmlElement(name = "FraudMitGrp")
    protected FraudMitGrp fraudMitGrp;

    /**
     * Gets the value of the commonGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CommonGrp }
     *     
     */
    public CommonGrp getCommonGrp() {
        return commonGrp;
    }

    /**
     * Sets the value of the commonGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommonGrp }
     *     
     */
    public void setCommonGrp(CommonGrp value) {
        this.commonGrp = value;
    }

    /**
     * Gets the value of the billPayGrp property.
     * 
     * @return
     *     possible object is
     *     {@link BillPayGrp }
     *     
     */
    public BillPayGrp getBillPayGrp() {
        return billPayGrp;
    }

    /**
     * Sets the value of the billPayGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillPayGrp }
     *     
     */
    public void setBillPayGrp(BillPayGrp value) {
        this.billPayGrp = value;
    }

    /**
     * Gets the value of the cardGrp property.
     * 
     * @return
     *     possible object is
     *     {@link CardGrp }
     *     
     */
    public CardGrp getCardGrp() {
        return cardGrp;
    }

    /**
     * Sets the value of the cardGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardGrp }
     *     
     */
    public void setCardGrp(CardGrp value) {
        this.cardGrp = value;
    }

    /**
     * Gets the value of the addtlAmtGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addtlAmtGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddtlAmtGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddtlAmtGrp }
     * 
     * 
     */
    public List<AddtlAmtGrp> getAddtlAmtGrp() {
        if (addtlAmtGrp == null) {
            addtlAmtGrp = new ArrayList<AddtlAmtGrp>();
        }
        return this.addtlAmtGrp;
    }

    /**
     * Gets the value of the emvGrp property.
     * 
     * @return
     *     possible object is
     *     {@link EMVGrp }
     *     
     */
    public EMVGrp getEMVGrp() {
        return emvGrp;
    }

    /**
     * Sets the value of the emvGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMVGrp }
     *     
     */
    public void setEMVGrp(EMVGrp value) {
        this.emvGrp = value;
    }

    /**
     * Gets the value of the taGrp property.
     * 
     * @return
     *     possible object is
     *     {@link TAGrp }
     *     
     */
    public TAGrp getTAGrp() {
        return taGrp;
    }

    /**
     * Sets the value of the taGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TAGrp }
     *     
     */
    public void setTAGrp(TAGrp value) {
        this.taGrp = value;
    }

    /**
     * Gets the value of the offerGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OfferGrp }
     *     
     */
    public OfferGrp getOfferGrp() {
        return offerGrp;
    }

    /**
     * Sets the value of the offerGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferGrp }
     *     
     */
    public void setOfferGrp(OfferGrp value) {
        this.offerGrp = value;
    }

    /**
     * Gets the value of the ecommGrp property.
     * 
     * @return
     *     possible object is
     *     {@link EcommGrp }
     *     
     */
    public EcommGrp getEcommGrp() {
        return ecommGrp;
    }

    /**
     * Sets the value of the ecommGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EcommGrp }
     *     
     */
    public void setEcommGrp(EcommGrp value) {
        this.ecommGrp = value;
    }

    /**
     * Gets the value of the secrTxnGrp property.
     * 
     * @return
     *     possible object is
     *     {@link SecrTxnGrp }
     *     
     */
    public SecrTxnGrp getSecrTxnGrp() {
        return secrTxnGrp;
    }

    /**
     * Sets the value of the secrTxnGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecrTxnGrp }
     *     
     */
    public void setSecrTxnGrp(SecrTxnGrp value) {
        this.secrTxnGrp = value;
    }

    /**
     * Gets the value of the visaGrp property.
     * 
     * @return
     *     possible object is
     *     {@link VisaGrp }
     *     
     */
    public VisaGrp getVisaGrp() {
        return visaGrp;
    }

    /**
     * Sets the value of the visaGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisaGrp }
     *     
     */
    public void setVisaGrp(VisaGrp value) {
        this.visaGrp = value;
    }

    /**
     * Gets the value of the mcGrp property.
     * 
     * @return
     *     possible object is
     *     {@link MCGrp }
     *     
     */
    public MCGrp getMCGrp() {
        return mcGrp;
    }

    /**
     * Sets the value of the mcGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link MCGrp }
     *     
     */
    public void setMCGrp(MCGrp value) {
        this.mcGrp = value;
    }

    /**
     * Gets the value of the dsGrp property.
     * 
     * @return
     *     possible object is
     *     {@link DSGrp }
     *     
     */
    public DSGrp getDSGrp() {
        return dsGrp;
    }

    /**
     * Sets the value of the dsGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link DSGrp }
     *     
     */
    public void setDSGrp(DSGrp value) {
        this.dsGrp = value;
    }

    /**
     * Gets the value of the amexGrp property.
     * 
     * @return
     *     possible object is
     *     {@link AmexGrp }
     *     
     */
    public AmexGrp getAmexGrp() {
        return amexGrp;
    }

    /**
     * Sets the value of the amexGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmexGrp }
     *     
     */
    public void setAmexGrp(AmexGrp value) {
        this.amexGrp = value;
    }

    /**
     * Gets the value of the respGrp property.
     * 
     * @return
     *     possible object is
     *     {@link RespGrp }
     *     
     */
    public RespGrp getRespGrp() {
        return respGrp;
    }

    /**
     * Sets the value of the respGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link RespGrp }
     *     
     */
    public void setRespGrp(RespGrp value) {
        this.respGrp = value;
    }

    /**
     * Gets the value of the origAuthGrp property.
     * 
     * @return
     *     possible object is
     *     {@link OrigAuthGrp }
     *     
     */
    public OrigAuthGrp getOrigAuthGrp() {
        return origAuthGrp;
    }

    /**
     * Sets the value of the origAuthGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrigAuthGrp }
     *     
     */
    public void setOrigAuthGrp(OrigAuthGrp value) {
        this.origAuthGrp = value;
    }

    /**
     * Gets the value of the fraudMitGrp property.
     * 
     * @return
     *     possible object is
     *     {@link FraudMitGrp }
     *     
     */
    public FraudMitGrp getFraudMitGrp() {
        return fraudMitGrp;
    }

    /**
     * Sets the value of the fraudMitGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link FraudMitGrp }
     *     
     */
    public void setFraudMitGrp(FraudMitGrp value) {
        this.fraudMitGrp = value;
    }

}
