//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DebitGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DebitGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}PayeePhoneNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}PayeeAcctNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}PayeeID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}DebitTraceNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}BillingInd" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DebitGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "payeePhoneNum",
    "payeeAcctNum",
    "payeeID",
    "debitTraceNum",
    "billingInd"
})
public class DebitGrp {

    @XmlElement(name = "PayeePhoneNum")
    protected String payeePhoneNum;
    @XmlElement(name = "PayeeAcctNum")
    protected String payeeAcctNum;
    @XmlElement(name = "PayeeID")
    protected String payeeID;
    @XmlElement(name = "DebitTraceNum")
    protected String debitTraceNum;
    @XmlElement(name = "BillingInd")
    protected BillingIndType billingInd;

    /**
     * Gets the value of the payeePhoneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeePhoneNum() {
        return payeePhoneNum;
    }

    /**
     * Sets the value of the payeePhoneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeePhoneNum(String value) {
        this.payeePhoneNum = value;
    }

    /**
     * Gets the value of the payeeAcctNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeAcctNum() {
        return payeeAcctNum;
    }

    /**
     * Sets the value of the payeeAcctNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeAcctNum(String value) {
        this.payeeAcctNum = value;
    }

    /**
     * Gets the value of the payeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPayeeID() {
        return payeeID;
    }

    /**
     * Sets the value of the payeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPayeeID(String value) {
        this.payeeID = value;
    }

    /**
     * Gets the value of the debitTraceNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDebitTraceNum() {
        return debitTraceNum;
    }

    /**
     * Sets the value of the debitTraceNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDebitTraceNum(String value) {
        this.debitTraceNum = value;
    }

    /**
     * Gets the value of the billingInd property.
     * 
     * @return
     *     possible object is
     *     {@link BillingIndType }
     *     
     */
    public BillingIndType getBillingInd() {
        return billingInd;
    }

    /**
     * Sets the value of the billingInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingIndType }
     *     
     */
    public void setBillingInd(BillingIndType value) {
        this.billingInd = value;
    }

}
