/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EMVGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = { "emvData",
        "cardSeqNum", "xCodeResp", "servCode", "appExpDate", "carc", "procInd", "procInfo" })
public class EMVGrp {

    @XmlElement(name = "EMVData", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String emvData;
    @XmlElement(name = "CardSeqNum", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String cardSeqNum;
    @XmlElement(name = "XCodeResp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String xCodeResp;
    @XmlElement(name = "ServCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String servCode;
    @XmlElement(name = "AppExpDate", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String appExpDate;
    @XmlElement(name = "CARC", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String carc;
    @XmlElement(name = "ProcInd", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String procInd;
    @XmlElement(name = "ProcInfo", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String procInfo;

    public String getEMVData() {
        return emvData;
    }

    public void setEMVData(String value) {
        this.emvData = value;
    }

    public String getCardSeqNum() {
        return cardSeqNum;
    }

    public void setCardSeqNum(String value) {
        this.cardSeqNum = value;
    }

    public String getXCodeResp() {
        return xCodeResp;
    }

    public void setXCodeResp(String value) {
        this.xCodeResp = value;
    }

    public String getServCode() {
        return servCode;
    }

    public void setServCode(String value) {
        this.servCode = value;
    }

    public String getAppExpDate() {
        return appExpDate;
    }

    public void setAppExpDate(String value) {
        this.appExpDate = value;
    }

    public String getCARC() {
        return carc;
    }

    public void setCARC(String value) {
        this.carc = value;
    }

    public String getProcInd() {
        return procInd;
    }

    public void setProcInd(String value) {
        this.procInd = value;
    }

    public String getProcInfo() {
        return procInfo;
    }

    public void setProcInfo(String value) {
        this.procInfo = value;
    }

}
