/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HostTotGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = {
        "totReqDate", "password", "netSettleAmt" })
public class HostTotGrp {

    @XmlElement(name = "TotReqDate", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String totReqDate;
    @XmlElement(name = "Password", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String password;
    @XmlElement(name = "NetSettleAmt", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String netSettleAmt;

    public String getTotReqDate() {
        return totReqDate;
    }

    public void setTotReqDate(String value) {
        this.totReqDate = value;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String value) {
        this.password = value;
    }

    public String getNetSettleAmt() {
        return netSettleAmt;
    }

    public void setNetSettleAmt(String value) {
        this.netSettleAmt = value;
    }

}
