/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TotReqDate_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TotReqDate");
    private final static QName _FPI_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "FPI");
    private final static QName _KeyID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "KeyID");
    private final static QName _DiscTransQualifier_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "DiscTransQualifier");
    private final static QName _Track1Data_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "Track1Data");
    private final static QName _VisaBID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "VisaBID");
    private final static QName _EBTType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EBTType");
    private final static QName _CardLevelResult_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "CardLevelResult");
    private final static QName _CurrFileCreationDt_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "CurrFileCreationDt");
    private final static QName _ReqFileOffset_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ReqFileOffset");
    private final static QName _SourceReasonCode_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "SourceReasonCode");
    private final static QName _DiscPOSData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DiscPOSData");
    private final static QName _MCSecrAD_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MCSecrAD");
    private final static QName _AmExTranID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AmExTranID");
    private final static QName _CardSeqNum_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardSeqNum");
    private final static QName _MerchCnty_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchCnty");
    private final static QName _HoldInfo_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "HoldInfo");
    private final static QName _PayeeID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "PayeeID");
    private final static QName _DiscProcCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DiscProcCode");
    private final static QName _UnitOfMsure_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "UnitOfMsure");
    private final static QName _EcommTxnInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EcommTxnInd");
    private final static QName _ChkSvcPvdr_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ChkSvcPvdr");
    private final static QName _VarCustRctTxt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "VarCustRctTxt");
    private final static QName _Safekey_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "Safekey");
    private final static QName _TAExpDate_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TAExpDate");
    private final static QName _EschtblTxn_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EschtblTxn");
    private final static QName _FrghtAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "FrghtAmt");
    private final static QName _MerchCatCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchCatCode");
    private final static QName _BillingInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "BillingInd");
    private final static QName _EncrptBlock_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EncrptBlock");
    private final static QName _DiscntAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DiscntAmt");
    private final static QName _LocalDateTime_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "LocalDateTime");
    private final static QName _SttlmDate_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "SttlmDate");
    private final static QName _ProgramID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ProgramID");
    private final static QName _UnitPrice_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "UnitPrice");
    private final static QName _EcommURL_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EcommURL");
    private final static QName _TrnmsnDateTime_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TrnmsnDateTime");
    private final static QName _DevTypeInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DevTypeInd");
    private final static QName _DutyAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DutyAmt");
    private final static QName _TermLocInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TermLocInd");
    private final static QName _BillPymtTxnInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "BillPymtTxnInd");
    private final static QName _Track2Data_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "Track2Data");
    private final static QName _VisaXID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "VisaXID");
    private final static QName _AmExPOSData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AmExPOSData");
    private final static QName _Tkn_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "Tkn");
    private final static QName _POSCondCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "POSCondCode");
    private final static QName _EMVData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EMVData");
    private final static QName _KeySerialNumData_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "KeySerialNumData");
    private final static QName _MerchAddr_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchAddr");
    private final static QName _MerchState_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchState");
    private final static QName _TASctyKey_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TASctyKey");
    private final static QName _VisaAUAR_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "VisaAUAR");
    private final static QName _TxnAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TxnAmt");
    private final static QName _CardExpiryDate_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardExpiryDate");
    private final static QName _MerchTaxID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchTaxID");
    private final static QName _RespCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "RespCode");
    private final static QName _MerchPostalCode_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "MerchPostalCode");
    private final static QName _TermCatCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TermCatCode");
    private final static QName _OfferResInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferResInd");
    private final static QName _CardTag_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardTag");
    private final static QName _DrvLic_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DrvLic");
    private final static QName _POSEntryModeChg_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "POSEntryModeChg");
    private final static QName _NextFileDLOffset_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "NextFileDLOffset");
    private final static QName _ServCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ServCode");
    private final static QName _Qnty_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "Qnty");
    private final static QName _OfferPubName_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferPubName");
    private final static QName _EncrptTrgt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EncrptTrgt");
    private final static QName _OrderDate_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OrderDate");
    private final static QName _OfferAmount_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferAmount");
    private final static QName _CardTxnAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardTxnAmt");
    private final static QName _VisaSecrTxnAD_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "VisaSecrTxnAD");
    private final static QName _MICR_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "MICR");
    private final static QName _PurchIdfr_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "PurchIdfr");
    private final static QName _AmexXID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AmexXID");
    private final static QName _TermEntryCapablt_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "TermEntryCapablt");
    private final static QName _CardCaptCap_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardCaptCap");
    private final static QName _OrderNum_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OrderNum");
    private final static QName _POSID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "POSID");
    private final static QName _ReceiptCopy_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ReceiptCopy");
    private final static QName _PINData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "PINData");
    private final static QName _CAVVResultCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CAVVResultCode");
    private final static QName _FBData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "FBData");
    private final static QName _AddAmtType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AddAmtType");
    private final static QName _CCVData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CCVData");
    private final static QName _NACSProdCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "NACSProdCode");
    private final static QName _ShipFromPostalCode_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "ShipFromPostalCode");
    private final static QName _TxnType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TxnType");
    private final static QName _AddAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AddAmt");
    private final static QName _RefNum_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "RefNum");
    private final static QName _AVSBillingPostalCode_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "AVSBillingPostalCode");
    private final static QName _ProcInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ProcInd");
    private final static QName _TermID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TermID");
    private final static QName _MerchCtry_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchCtry");
    private final static QName _AVSResultCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AVSResultCode");
    private final static QName _CardClass_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardClass");
    private final static QName _MCMSDI_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MCMSDI");
    private final static QName _CCVInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CCVInd");
    private final static QName _FunCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "FunCode");
    private final static QName _TxnCrncy_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TxnCrncy");
    private final static QName _FileType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "FileType");
    private final static QName _AddtlRespData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AddtlRespData");
    private final static QName _OfferID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferID");
    private final static QName _CardCost_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardCost");
    private final static QName _CCVResultCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CCVResultCode");
    private final static QName _OfferProvID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferProvID");
    private final static QName _OfferProvName_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferProvName");
    private final static QName _STAN_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "STAN");
    private final static QName _ServLvl_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ServLvl");
    private final static QName _AcctNum_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AcctNum");
    private final static QName _SctyLvl_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "SctyLvl");
    private final static QName _CustSvcPhoneNumber_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "CustSvcPhoneNumber");
    private final static QName _OrigTranDateTime_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "OrigTranDateTime");
    private final static QName _AppExpDate_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AppExpDate");
    private final static QName _AddAmtAcctType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AddAmtAcctType");
    private final static QName _DestCtryCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DestCtryCode");
    private final static QName _TPPID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "TPPID");
    private final static QName _GroupID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "GroupID");
    private final static QName _POSOfferCap_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "POSOfferCap");
    private final static QName _OfferPubID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferPubID");
    private final static QName _ReversalInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ReversalInd");
    private final static QName _MerchName_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchName");
    private final static QName _FileSize_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "FileSize");
    private final static QName _TransID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TransID");
    private final static QName _CARC_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "CARC");
    private final static QName _DiscRespCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DiscRespCode");
    private final static QName _PayeePhoneNum_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "PayeePhoneNum");
    private final static QName _MCPOSData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MCPOSData");
    private final static QName _ErrorData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ErrorData");
    private final static QName _AmexSecrAD_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AmexSecrAD");
    private final static QName _XCodeResp_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "XCodeResp");
    private final static QName _ReqFBMaxSize_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ReqFBMaxSize");
    private final static QName _FACode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "FACode");
    private final static QName _Password_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "Password");
    private final static QName _DestPostalCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DestPostalCode");
    private final static QName _ExistingDebtInd_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "ExistingDebtInd");
    private final static QName _AddAmtCrncy_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AddAmtCrncy");
    private final static QName _DLDateOfBirth_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DLDateOfBirth");
    private final static QName _OrigRespCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OrigRespCode");
    private final static QName _DiscPOSEntry_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DiscPOSEntry");
    private final static QName _AthNtwkID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AthNtwkID");
    private final static QName _CCVErrorCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CCVErrorCode");
    private final static QName _BanknetData_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "BanknetData");
    private final static QName _StateCode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "StateCode");
    private final static QName _NumOfProds_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "NumOfProds");
    private final static QName _AltMerchID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AltMerchID");
    private final static QName _AVSBillingAddr_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AVSBillingAddr");
    private final static QName _DiscNRID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "DiscNRID");
    private final static QName _PymtType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "PymtType");
    private final static QName _ACI_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "ACI");
    private final static QName _OrigLocalDateTime_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "OrigLocalDateTime");
    private final static QName _MerchAdviceCode_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "MerchAdviceCode");
    private final static QName _NetSettleAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "NetSettleAmt");
    private final static QName _EncrptType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "EncrptType");
    private final static QName _AuthID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "AuthID");
    private final static QName _SctyKeyUpdInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "SctyKeyUpdInd");
    private final static QName _GMF_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "GMF");
    private final static QName _SettleInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "SettleInd");
    private final static QName _CardType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardType");
    private final static QName _POSEntryMode_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "POSEntryMode");
    private final static QName _PCOrderNum_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "PCOrderNum");
    private final static QName _TranEditErrCode_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "TranEditErrCode");
    private final static QName _OfferDesc_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OfferDesc");
    private final static QName _TaxAmtCapablt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TaxAmtCapablt");
    private final static QName _ChkEntryMethod_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ChkEntryMethod");
    private final static QName _PartAuthrztnApprvlCapablt_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "PartAuthrztnApprvlCapablt");
    private final static QName _TknType_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TknType");
    private final static QName _FBSeq_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "FBSeq");
    private final static QName _UCAFCollectInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "UCAFCollectInd");
    private final static QName _ProcInfo_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ProcInfo");
    private final static QName _MerchCity_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchCity");
    private final static QName _ProdDesc_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ProdDesc");
    private final static QName _TaxAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TaxAmt");
    private final static QName _OrigAuthID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OrigAuthID");
    private final static QName _ProdAmt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "ProdAmt");
    private final static QName _PayeeAcctNum_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "PayeeAcctNum");
    private final static QName _FileCRC16_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "FileCRC16");
    private final static QName _TaxInd_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "TaxInd");
    private final static QName _OrigSTAN_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "OrigSTAN");
    private final static QName _TxnCt_QNAME = new QName("com/firstdata/Merchant/gmfV2.08", "TxnCt");
    private final static QName _MerchantID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchantID");
    private final static QName _MrktSpecificDataInd_QNAME = new QName(
            "com/firstdata/Merchant/gmfV2.08", "MrktSpecificDataInd");
    private final static QName _CardActivDate_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "CardActivDate");
    private final static QName _MerchID_QNAME = new QName("com/firstdata/Merchant/gmfV2.08",
            "MerchID");

    public ObjectFactory() {
    }

    public OrderGrp createOrderGrp() {
        return new OrderGrp();
    }

    public DebitGrp createDebitGrp() {
        return new DebitGrp();
    }

    public BillPayGrp createBillPayGrp() {
        return new BillPayGrp();
    }

    public CustInfoGrp createCustInfoGrp() {
        return new CustInfoGrp();
    }

    public ProdCodeDetGrp createProdCodeDetGrp() {
        return new ProdCodeDetGrp();
    }

    public DSGrp createDSGrp() {
        return new DSGrp();
    }

    public FileDLGrp createFileDLGrp() {
        return new FileDLGrp();
    }

    public CheckGrp createCheckGrp() {
        return new CheckGrp();
    }

    public CommonGrp createCommonGrp() {
        return new CommonGrp();
    }

    public CreditRequestDetails createCreditRequestDetails() {
        return new CreditRequestDetails();
    }

    public HostTotGrp createHostTotGrp() {
        return new HostTotGrp();
    }

    public PurchCardlvl2Grp createPurchCardlvl2Grp() {
        return new PurchCardlvl2Grp();
    }

    public RejectResponseDetails createRejectResponseDetails() {
        return new RejectResponseDetails();
    }

    public StoredValueGrp createStoredValueGrp() {
        return new StoredValueGrp();
    }

    public AmexGrp createAmexGrp() {
        return new AmexGrp();
    }

    public VoidTOReversalRequestDetails createVoidTOReversalRequestDetails() {
        return new VoidTOReversalRequestDetails();
    }

    public EbtGrp createEbtGrp() {
        return new EbtGrp();
    }

    public PrepaidResponseDetails createPrepaidResponseDetails() {
        return new PrepaidResponseDetails();
    }

    public GenPrepaidRequestDetails createGenPrepaidRequestDetails() {
        return new GenPrepaidRequestDetails();
    }

    public CreditResponseDetails createCreditResponseDetails() {
        return new CreditResponseDetails();
    }

    public VisaGrp createVisaGrp() {
        return new VisaGrp();
    }

    public DebitResponseDetails createDebitResponseDetails() {
        return new DebitResponseDetails();
    }

    public RespGrp createRespGrp() {
        return new RespGrp();
    }

    public VoidTOReversalResponseDetails createVoidTOReversalResponseDetails() {
        return new VoidTOReversalResponseDetails();
    }

    public PrepaidRequestDetails createPrepaidRequestDetails() {
        return new PrepaidRequestDetails();
    }

    public CheckResponseDetails createCheckResponseDetails() {
        return new CheckResponseDetails();
    }

    public OfferGrp createOfferGrp() {
        return new OfferGrp();
    }

    public PrivateLabelRequestDetails createPrivateLabelRequestDetails() {
        return new PrivateLabelRequestDetails();
    }

    public HostTotDetGrp createHostTotDetGrp() {
        return new HostTotDetGrp();
    }

    public SecrTxnGrp createSecrTxnGrp() {
        return new SecrTxnGrp();
    }

    public PrivateLabelResponseDetails createPrivateLabelResponseDetails() {
        return new PrivateLabelResponseDetails();
    }

    public PINGrp createPINGrp() {
        return new PINGrp();
    }

    public MCGrp createMCGrp() {
        return new MCGrp();
    }

    public TAGrp createTAGrp() {
        return new TAGrp();
    }

    public AdminResponseDetails createAdminResponseDetails() {
        return new AdminResponseDetails();
    }

    public GMFMessageVariants createGMFMessageVariants() {
        return new GMFMessageVariants();
    }

    public DebitRequestDetails createDebitRequestDetails() {
        return new DebitRequestDetails();
    }

    public OrigAuthGrp createOrigAuthGrp() {
        return new OrigAuthGrp();
    }

    public ProdCodeGrp createProdCodeGrp() {
        return new ProdCodeGrp();
    }

    public EcommGrp createEcommGrp() {
        return new EcommGrp();
    }

    public EBTRequestDetails createEBTRequestDetails() {
        return new EBTRequestDetails();
    }

    public PinlessDebitResponseDetails createPinlessDebitResponseDetails() {
        return new PinlessDebitResponseDetails();
    }

    public AddtlAmtGrp createAddtlAmtGrp() {
        return new AddtlAmtGrp();
    }

    public PinlessDebitRequestDetails createPinlessDebitRequestDetails() {
        return new PinlessDebitRequestDetails();
    }

    public TARequestDetails createTARequestDetails() {
        return new TARequestDetails();
    }

    public EBTResponseDetails createEBTResponseDetails() {
        return new EBTResponseDetails();
    }

    public CheckRequestDetails createCheckRequestDetails() {
        return new CheckRequestDetails();
    }

    public TAResponseDetails createTAResponseDetails() {
        return new TAResponseDetails();
    }

    public AdminRequestDetails createAdminRequestDetails() {
        return new AdminRequestDetails();
    }

    public GenPrepaidResponseDetails createGenPrepaidResponseDetails() {
        return new GenPrepaidResponseDetails();
    }

    public EMVGrp createEMVGrp() {
        return new EMVGrp();
    }

    public AltMerchNameAndAddrGrp createAltMerchNameAndAddrGrp() {
        return new AltMerchNameAndAddrGrp();
    }

    public CardGrp createCardGrp() {
        return new CardGrp();
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TotReqDate")
    public JAXBElement<String> createTotReqDate(String value) {
        return new JAXBElement<String>(_TotReqDate_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FPI")
    public JAXBElement<String> createFPI(String value) {
        return new JAXBElement<String>(_FPI_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "KeyID")
    public JAXBElement<String> createKeyID(String value) {
        return new JAXBElement<String>(_KeyID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DiscTransQualifier")
    public JAXBElement<String> createDiscTransQualifier(String value) {
        return new JAXBElement<String>(_DiscTransQualifier_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "Track1Data")
    public JAXBElement<String> createTrack1Data(String value) {
        return new JAXBElement<String>(_Track1Data_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "VisaBID")
    public JAXBElement<String> createVisaBID(String value) {
        return new JAXBElement<String>(_VisaBID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EBTType")
    public JAXBElement<EBTTypeType> createEBTType(EBTTypeType value) {
        return new JAXBElement<EBTTypeType>(_EBTType_QNAME, EBTTypeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardLevelResult")
    public JAXBElement<String> createCardLevelResult(String value) {
        return new JAXBElement<String>(_CardLevelResult_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CurrFileCreationDt")
    public JAXBElement<String> createCurrFileCreationDt(String value) {
        return new JAXBElement<String>(_CurrFileCreationDt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ReqFileOffset")
    public JAXBElement<String> createReqFileOffset(String value) {
        return new JAXBElement<String>(_ReqFileOffset_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "SourceReasonCode")
    public JAXBElement<String> createSourceReasonCode(String value) {
        return new JAXBElement<String>(_SourceReasonCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DiscPOSData")
    public JAXBElement<String> createDiscPOSData(String value) {
        return new JAXBElement<String>(_DiscPOSData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MCSecrAD")
    public JAXBElement<String> createMCSecrAD(String value) {
        return new JAXBElement<String>(_MCSecrAD_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AmExTranID")
    public JAXBElement<String> createAmExTranID(String value) {
        return new JAXBElement<String>(_AmExTranID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardSeqNum")
    public JAXBElement<String> createCardSeqNum(String value) {
        return new JAXBElement<String>(_CardSeqNum_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchCnty")
    public JAXBElement<String> createMerchCnty(String value) {
        return new JAXBElement<String>(_MerchCnty_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "HoldInfo")
    public JAXBElement<String> createHoldInfo(String value) {
        return new JAXBElement<String>(_HoldInfo_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "PayeeID")
    public JAXBElement<String> createPayeeID(String value) {
        return new JAXBElement<String>(_PayeeID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DiscProcCode")
    public JAXBElement<String> createDiscProcCode(String value) {
        return new JAXBElement<String>(_DiscProcCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "UnitOfMsure")
    public JAXBElement<String> createUnitOfMsure(String value) {
        return new JAXBElement<String>(_UnitOfMsure_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EcommTxnInd")
    public JAXBElement<String> createEcommTxnInd(String value) {
        return new JAXBElement<String>(_EcommTxnInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ChkSvcPvdr")
    public JAXBElement<ChkSvcPvdrType> createChkSvcPvdr(ChkSvcPvdrType value) {
        return new JAXBElement<ChkSvcPvdrType>(_ChkSvcPvdr_QNAME, ChkSvcPvdrType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "VarCustRctTxt")
    public JAXBElement<String> createVarCustRctTxt(String value) {
        return new JAXBElement<String>(_VarCustRctTxt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "Safekey")
    public JAXBElement<String> createSafekey(String value) {
        return new JAXBElement<String>(_Safekey_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TAExpDate")
    public JAXBElement<String> createTAExpDate(String value) {
        return new JAXBElement<String>(_TAExpDate_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EschtblTxn")
    public JAXBElement<EschtblTxnType> createEschtblTxn(EschtblTxnType value) {
        return new JAXBElement<EschtblTxnType>(_EschtblTxn_QNAME, EschtblTxnType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FrghtAmt")
    public JAXBElement<String> createFrghtAmt(String value) {
        return new JAXBElement<String>(_FrghtAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchCatCode")
    public JAXBElement<String> createMerchCatCode(String value) {
        return new JAXBElement<String>(_MerchCatCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "BillingInd")
    public JAXBElement<String> createBillingInd(String value) {
        return new JAXBElement<String>(_BillingInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EncrptBlock")
    public JAXBElement<String> createEncrptBlock(String value) {
        return new JAXBElement<String>(_EncrptBlock_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DiscntAmt")
    public JAXBElement<String> createDiscntAmt(String value) {
        return new JAXBElement<String>(_DiscntAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "LocalDateTime")
    public JAXBElement<String> createLocalDateTime(String value) {
        return new JAXBElement<String>(_LocalDateTime_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "SttlmDate")
    public JAXBElement<String> createSttlmDate(String value) {
        return new JAXBElement<String>(_SttlmDate_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ProgramID")
    public JAXBElement<ProgramIDType> createProgramID(ProgramIDType value) {
        return new JAXBElement<ProgramIDType>(_ProgramID_QNAME, ProgramIDType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "UnitPrice")
    public JAXBElement<String> createUnitPrice(String value) {
        return new JAXBElement<String>(_UnitPrice_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EcommURL")
    public JAXBElement<String> createEcommURL(String value) {
        return new JAXBElement<String>(_EcommURL_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TrnmsnDateTime")
    public JAXBElement<String> createTrnmsnDateTime(String value) {
        return new JAXBElement<String>(_TrnmsnDateTime_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DevTypeInd")
    public JAXBElement<String> createDevTypeInd(String value) {
        return new JAXBElement<String>(_DevTypeInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DutyAmt")
    public JAXBElement<String> createDutyAmt(String value) {
        return new JAXBElement<String>(_DutyAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TermLocInd")
    public JAXBElement<String> createTermLocInd(String value) {
        return new JAXBElement<String>(_TermLocInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "BillPymtTxnInd")
    public JAXBElement<BillPymtTxnIndType> createBillPymtTxnInd(BillPymtTxnIndType value) {
        return new JAXBElement<BillPymtTxnIndType>(_BillPymtTxnInd_QNAME, BillPymtTxnIndType.class,
                null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "Track2Data")
    public JAXBElement<String> createTrack2Data(String value) {
        return new JAXBElement<String>(_Track2Data_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "VisaXID")
    public JAXBElement<String> createVisaXID(String value) {
        return new JAXBElement<String>(_VisaXID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AmExPOSData")
    public JAXBElement<String> createAmExPOSData(String value) {
        return new JAXBElement<String>(_AmExPOSData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "Tkn")
    public JAXBElement<String> createTkn(String value) {
        return new JAXBElement<String>(_Tkn_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "POSCondCode")
    public JAXBElement<String> createPOSCondCode(String value) {
        return new JAXBElement<String>(_POSCondCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EMVData")
    public JAXBElement<String> createEMVData(String value) {
        return new JAXBElement<String>(_EMVData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "KeySerialNumData")
    public JAXBElement<String> createKeySerialNumData(String value) {
        return new JAXBElement<String>(_KeySerialNumData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchAddr")
    public JAXBElement<String> createMerchAddr(String value) {
        return new JAXBElement<String>(_MerchAddr_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchState")
    public JAXBElement<String> createMerchState(String value) {
        return new JAXBElement<String>(_MerchState_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TASctyKey")
    public JAXBElement<String> createTASctyKey(String value) {
        return new JAXBElement<String>(_TASctyKey_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "VisaAUAR")
    public JAXBElement<String> createVisaAUAR(String value) {
        return new JAXBElement<String>(_VisaAUAR_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TxnAmt")
    public JAXBElement<String> createTxnAmt(String value) {
        return new JAXBElement<String>(_TxnAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardExpiryDate")
    public JAXBElement<String> createCardExpiryDate(String value) {
        return new JAXBElement<String>(_CardExpiryDate_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchTaxID")
    public JAXBElement<String> createMerchTaxID(String value) {
        return new JAXBElement<String>(_MerchTaxID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "RespCode")
    public JAXBElement<String> createRespCode(String value) {
        return new JAXBElement<String>(_RespCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchPostalCode")
    public JAXBElement<String> createMerchPostalCode(String value) {
        return new JAXBElement<String>(_MerchPostalCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TermCatCode")
    public JAXBElement<String> createTermCatCode(String value) {
        return new JAXBElement<String>(_TermCatCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferResInd")
    public JAXBElement<String> createOfferResInd(String value) {
        return new JAXBElement<String>(_OfferResInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardTag")
    public JAXBElement<String> createCardTag(String value) {
        return new JAXBElement<String>(_CardTag_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DrvLic")
    public JAXBElement<String> createDrvLic(String value) {
        return new JAXBElement<String>(_DrvLic_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "POSEntryModeChg")
    public JAXBElement<POSEntryModeChgType> createPOSEntryModeChg(POSEntryModeChgType value) {
        return new JAXBElement<POSEntryModeChgType>(_POSEntryModeChg_QNAME,
                POSEntryModeChgType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "NextFileDLOffset")
    public JAXBElement<String> createNextFileDLOffset(String value) {
        return new JAXBElement<String>(_NextFileDLOffset_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ServCode")
    public JAXBElement<String> createServCode(String value) {
        return new JAXBElement<String>(_ServCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "Qnty")
    public JAXBElement<String> createQnty(String value) {
        return new JAXBElement<String>(_Qnty_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferPubName")
    public JAXBElement<String> createOfferPubName(String value) {
        return new JAXBElement<String>(_OfferPubName_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EncrptTrgt")
    public JAXBElement<EncrptTrgtType> createEncrptTrgt(EncrptTrgtType value) {
        return new JAXBElement<EncrptTrgtType>(_EncrptTrgt_QNAME, EncrptTrgtType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OrderDate")
    public JAXBElement<String> createOrderDate(String value) {
        return new JAXBElement<String>(_OrderDate_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferAmount")
    public JAXBElement<String> createOfferAmount(String value) {
        return new JAXBElement<String>(_OfferAmount_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardTxnAmt")
    public JAXBElement<String> createCardTxnAmt(String value) {
        return new JAXBElement<String>(_CardTxnAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "VisaSecrTxnAD")
    public JAXBElement<String> createVisaSecrTxnAD(String value) {
        return new JAXBElement<String>(_VisaSecrTxnAD_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MICR")
    public JAXBElement<String> createMICR(String value) {
        return new JAXBElement<String>(_MICR_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "PurchIdfr")
    public JAXBElement<String> createPurchIdfr(String value) {
        return new JAXBElement<String>(_PurchIdfr_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AmexXID")
    public JAXBElement<String> createAmexXID(String value) {
        return new JAXBElement<String>(_AmexXID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TermEntryCapablt")
    public JAXBElement<String> createTermEntryCapablt(String value) {
        return new JAXBElement<String>(_TermEntryCapablt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardCaptCap")
    public JAXBElement<String> createCardCaptCap(String value) {
        return new JAXBElement<String>(_CardCaptCap_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OrderNum")
    public JAXBElement<String> createOrderNum(String value) {
        return new JAXBElement<String>(_OrderNum_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "POSID")
    public JAXBElement<String> createPOSID(String value) {
        return new JAXBElement<String>(_POSID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ReceiptCopy")
    public JAXBElement<String> createReceiptCopy(String value) {
        return new JAXBElement<String>(_ReceiptCopy_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "PINData")
    public JAXBElement<String> createPINData(String value) {
        return new JAXBElement<String>(_PINData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CAVVResultCode")
    public JAXBElement<String> createCAVVResultCode(String value) {
        return new JAXBElement<String>(_CAVVResultCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FBData")
    public JAXBElement<String> createFBData(String value) {
        return new JAXBElement<String>(_FBData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AddAmtType")
    public JAXBElement<AddAmtTypeType> createAddAmtType(AddAmtTypeType value) {
        return new JAXBElement<AddAmtTypeType>(_AddAmtType_QNAME, AddAmtTypeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CCVData")
    public JAXBElement<String> createCCVData(String value) {
        return new JAXBElement<String>(_CCVData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "NACSProdCode")
    public JAXBElement<String> createNACSProdCode(String value) {
        return new JAXBElement<String>(_NACSProdCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ShipFromPostalCode")
    public JAXBElement<String> createShipFromPostalCode(String value) {
        return new JAXBElement<String>(_ShipFromPostalCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TxnType")
    public JAXBElement<TxnTypeType> createTxnType(TxnTypeType value) {
        return new JAXBElement<TxnTypeType>(_TxnType_QNAME, TxnTypeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AddAmt")
    public JAXBElement<String> createAddAmt(String value) {
        return new JAXBElement<String>(_AddAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "RefNum")
    public JAXBElement<String> createRefNum(String value) {
        return new JAXBElement<String>(_RefNum_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AVSBillingPostalCode")
    public JAXBElement<String> createAVSBillingPostalCode(String value) {
        return new JAXBElement<String>(_AVSBillingPostalCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ProcInd")
    public JAXBElement<String> createProcInd(String value) {
        return new JAXBElement<String>(_ProcInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TermID")
    public JAXBElement<String> createTermID(String value) {
        return new JAXBElement<String>(_TermID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchCtry")
    public JAXBElement<String> createMerchCtry(String value) {
        return new JAXBElement<String>(_MerchCtry_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AVSResultCode")
    public JAXBElement<AVSResultCodeType> createAVSResultCode(AVSResultCodeType value) {
        return new JAXBElement<AVSResultCodeType>(_AVSResultCode_QNAME, AVSResultCodeType.class,
                null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardClass")
    public JAXBElement<String> createCardClass(String value) {
        return new JAXBElement<String>(_CardClass_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MCMSDI")
    public JAXBElement<MCMSDIType> createMCMSDI(MCMSDIType value) {
        return new JAXBElement<MCMSDIType>(_MCMSDI_QNAME, MCMSDIType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CCVInd")
    public JAXBElement<CCVIndType> createCCVInd(CCVIndType value) {
        return new JAXBElement<CCVIndType>(_CCVInd_QNAME, CCVIndType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FunCode")
    public JAXBElement<FunCodeType> createFunCode(FunCodeType value) {
        return new JAXBElement<FunCodeType>(_FunCode_QNAME, FunCodeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TxnCrncy")
    public JAXBElement<String> createTxnCrncy(String value) {
        return new JAXBElement<String>(_TxnCrncy_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FileType")
    public JAXBElement<FileTypeType> createFileType(FileTypeType value) {
        return new JAXBElement<FileTypeType>(_FileType_QNAME, FileTypeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AddtlRespData")
    public JAXBElement<String> createAddtlRespData(String value) {
        return new JAXBElement<String>(_AddtlRespData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferID")
    public JAXBElement<String> createOfferID(String value) {
        return new JAXBElement<String>(_OfferID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardCost")
    public JAXBElement<String> createCardCost(String value) {
        return new JAXBElement<String>(_CardCost_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CCVResultCode")
    public JAXBElement<CCVResultCodeType> createCCVResultCode(CCVResultCodeType value) {
        return new JAXBElement<CCVResultCodeType>(_CCVResultCode_QNAME, CCVResultCodeType.class,
                null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferProvID")
    public JAXBElement<String> createOfferProvID(String value) {
        return new JAXBElement<String>(_OfferProvID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferProvName")
    public JAXBElement<String> createOfferProvName(String value) {
        return new JAXBElement<String>(_OfferProvName_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "STAN")
    public JAXBElement<String> createSTAN(String value) {
        return new JAXBElement<String>(_STAN_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ServLvl")
    public JAXBElement<String> createServLvl(String value) {
        return new JAXBElement<String>(_ServLvl_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AcctNum")
    public JAXBElement<String> createAcctNum(String value) {
        return new JAXBElement<String>(_AcctNum_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "SctyLvl")
    public JAXBElement<SctyLvlType> createSctyLvl(SctyLvlType value) {
        return new JAXBElement<SctyLvlType>(_SctyLvl_QNAME, SctyLvlType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CustSvcPhoneNumber")
    public JAXBElement<String> createCustSvcPhoneNumber(String value) {
        return new JAXBElement<String>(_CustSvcPhoneNumber_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OrigTranDateTime")
    public JAXBElement<String> createOrigTranDateTime(String value) {
        return new JAXBElement<String>(_OrigTranDateTime_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AppExpDate")
    public JAXBElement<String> createAppExpDate(String value) {
        return new JAXBElement<String>(_AppExpDate_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AddAmtAcctType")
    public JAXBElement<String> createAddAmtAcctType(String value) {
        return new JAXBElement<String>(_AddAmtAcctType_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DestCtryCode")
    public JAXBElement<String> createDestCtryCode(String value) {
        return new JAXBElement<String>(_DestCtryCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TPPID")
    public JAXBElement<String> createTPPID(String value) {
        return new JAXBElement<String>(_TPPID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "GroupID")
    public JAXBElement<String> createGroupID(String value) {
        return new JAXBElement<String>(_GroupID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "POSOfferCap")
    public JAXBElement<String> createPOSOfferCap(String value) {
        return new JAXBElement<String>(_POSOfferCap_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferPubID")
    public JAXBElement<String> createOfferPubID(String value) {
        return new JAXBElement<String>(_OfferPubID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ReversalInd")
    public JAXBElement<ReversalIndType> createReversalInd(ReversalIndType value) {
        return new JAXBElement<ReversalIndType>(_ReversalInd_QNAME, ReversalIndType.class, null,
                value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchName")
    public JAXBElement<String> createMerchName(String value) {
        return new JAXBElement<String>(_MerchName_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FileSize")
    public JAXBElement<String> createFileSize(String value) {
        return new JAXBElement<String>(_FileSize_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TransID")
    public JAXBElement<String> createTransID(String value) {
        return new JAXBElement<String>(_TransID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CARC")
    public JAXBElement<String> createCARC(String value) {
        return new JAXBElement<String>(_CARC_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DiscRespCode")
    public JAXBElement<String> createDiscRespCode(String value) {
        return new JAXBElement<String>(_DiscRespCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "PayeePhoneNum")
    public JAXBElement<String> createPayeePhoneNum(String value) {
        return new JAXBElement<String>(_PayeePhoneNum_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MCPOSData")
    public JAXBElement<String> createMCPOSData(String value) {
        return new JAXBElement<String>(_MCPOSData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ErrorData")
    public JAXBElement<String> createErrorData(String value) {
        return new JAXBElement<String>(_ErrorData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AmexSecrAD")
    public JAXBElement<String> createAmexSecrAD(String value) {
        return new JAXBElement<String>(_AmexSecrAD_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "XCodeResp")
    public JAXBElement<String> createXCodeResp(String value) {
        return new JAXBElement<String>(_XCodeResp_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ReqFBMaxSize")
    public JAXBElement<String> createReqFBMaxSize(String value) {
        return new JAXBElement<String>(_ReqFBMaxSize_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FACode")
    public JAXBElement<String> createFACode(String value) {
        return new JAXBElement<String>(_FACode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "Password")
    public JAXBElement<String> createPassword(String value) {
        return new JAXBElement<String>(_Password_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DestPostalCode")
    public JAXBElement<String> createDestPostalCode(String value) {
        return new JAXBElement<String>(_DestPostalCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ExistingDebtInd")
    public JAXBElement<String> createExistingDebtInd(String value) {
        return new JAXBElement<String>(_ExistingDebtInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AddAmtCrncy")
    public JAXBElement<String> createAddAmtCrncy(String value) {
        return new JAXBElement<String>(_AddAmtCrncy_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DLDateOfBirth")
    public JAXBElement<String> createDLDateOfBirth(String value) {
        return new JAXBElement<String>(_DLDateOfBirth_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OrigRespCode")
    public JAXBElement<String> createOrigRespCode(String value) {
        return new JAXBElement<String>(_OrigRespCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DiscPOSEntry")
    public JAXBElement<String> createDiscPOSEntry(String value) {
        return new JAXBElement<String>(_DiscPOSEntry_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AthNtwkID")
    public JAXBElement<String> createAthNtwkID(String value) {
        return new JAXBElement<String>(_AthNtwkID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CCVErrorCode")
    public JAXBElement<CCVErrorCodeType> createCCVErrorCode(CCVErrorCodeType value) {
        return new JAXBElement<CCVErrorCodeType>(_CCVErrorCode_QNAME, CCVErrorCodeType.class, null,
                value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "BanknetData")
    public JAXBElement<String> createBanknetData(String value) {
        return new JAXBElement<String>(_BanknetData_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "StateCode")
    public JAXBElement<String> createStateCode(String value) {
        return new JAXBElement<String>(_StateCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "NumOfProds")
    public JAXBElement<String> createNumOfProds(String value) {
        return new JAXBElement<String>(_NumOfProds_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AltMerchID")
    public JAXBElement<String> createAltMerchID(String value) {
        return new JAXBElement<String>(_AltMerchID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AVSBillingAddr")
    public JAXBElement<String> createAVSBillingAddr(String value) {
        return new JAXBElement<String>(_AVSBillingAddr_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "DiscNRID")
    public JAXBElement<String> createDiscNRID(String value) {
        return new JAXBElement<String>(_DiscNRID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "PymtType")
    public JAXBElement<PymtTypeType> createPymtType(PymtTypeType value) {
        return new JAXBElement<PymtTypeType>(_PymtType_QNAME, PymtTypeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ACI")
    public JAXBElement<ACIType> createACI(ACIType value) {
        return new JAXBElement<ACIType>(_ACI_QNAME, ACIType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OrigLocalDateTime")
    public JAXBElement<String> createOrigLocalDateTime(String value) {
        return new JAXBElement<String>(_OrigLocalDateTime_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchAdviceCode")
    public JAXBElement<String> createMerchAdviceCode(String value) {
        return new JAXBElement<String>(_MerchAdviceCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "NetSettleAmt")
    public JAXBElement<String> createNetSettleAmt(String value) {
        return new JAXBElement<String>(_NetSettleAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "EncrptType")
    public JAXBElement<EncrptTypeType> createEncrptType(EncrptTypeType value) {
        return new JAXBElement<EncrptTypeType>(_EncrptType_QNAME, EncrptTypeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "AuthID")
    public JAXBElement<String> createAuthID(String value) {
        return new JAXBElement<String>(_AuthID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "SctyKeyUpdInd")
    public JAXBElement<String> createSctyKeyUpdInd(String value) {
        return new JAXBElement<String>(_SctyKeyUpdInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "GMF")
    public JAXBElement<GMFMessageVariants> createGMF(GMFMessageVariants value) {
        return new JAXBElement<GMFMessageVariants>(_GMF_QNAME, GMFMessageVariants.class, null,
                value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "SettleInd")
    public JAXBElement<String> createSettleInd(String value) {
        return new JAXBElement<String>(_SettleInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardType")
    public JAXBElement<CardTypeType> createCardType(CardTypeType value) {
        return new JAXBElement<CardTypeType>(_CardType_QNAME, CardTypeType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "POSEntryMode")
    public JAXBElement<String> createPOSEntryMode(String value) {
        return new JAXBElement<String>(_POSEntryMode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "PCOrderNum")
    public JAXBElement<String> createPCOrderNum(String value) {
        return new JAXBElement<String>(_PCOrderNum_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TranEditErrCode")
    public JAXBElement<String> createTranEditErrCode(String value) {
        return new JAXBElement<String>(_TranEditErrCode_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OfferDesc")
    public JAXBElement<String> createOfferDesc(String value) {
        return new JAXBElement<String>(_OfferDesc_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TaxAmtCapablt")
    public JAXBElement<String> createTaxAmtCapablt(String value) {
        return new JAXBElement<String>(_TaxAmtCapablt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ChkEntryMethod")
    public JAXBElement<String> createChkEntryMethod(String value) {
        return new JAXBElement<String>(_ChkEntryMethod_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08",
            name = "PartAuthrztnApprvlCapablt")
    public JAXBElement<String> createPartAuthrztnApprvlCapablt(String value) {
        return new JAXBElement<String>(_PartAuthrztnApprvlCapablt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TknType")
    public JAXBElement<String> createTknType(String value) {
        return new JAXBElement<String>(_TknType_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FBSeq")
    public JAXBElement<String> createFBSeq(String value) {
        return new JAXBElement<String>(_FBSeq_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "UCAFCollectInd")
    public JAXBElement<String> createUCAFCollectInd(String value) {
        return new JAXBElement<String>(_UCAFCollectInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ProcInfo")
    public JAXBElement<String> createProcInfo(String value) {
        return new JAXBElement<String>(_ProcInfo_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchCity")
    public JAXBElement<String> createMerchCity(String value) {
        return new JAXBElement<String>(_MerchCity_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ProdDesc")
    public JAXBElement<String> createProdDesc(String value) {
        return new JAXBElement<String>(_ProdDesc_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TaxAmt")
    public JAXBElement<String> createTaxAmt(String value) {
        return new JAXBElement<String>(_TaxAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OrigAuthID")
    public JAXBElement<String> createOrigAuthID(String value) {
        return new JAXBElement<String>(_OrigAuthID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "ProdAmt")
    public JAXBElement<String> createProdAmt(String value) {
        return new JAXBElement<String>(_ProdAmt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "PayeeAcctNum")
    public JAXBElement<String> createPayeeAcctNum(String value) {
        return new JAXBElement<String>(_PayeeAcctNum_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "FileCRC16")
    public JAXBElement<String> createFileCRC16(String value) {
        return new JAXBElement<String>(_FileCRC16_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TaxInd")
    public JAXBElement<String> createTaxInd(String value) {
        return new JAXBElement<String>(_TaxInd_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "OrigSTAN")
    public JAXBElement<String> createOrigSTAN(String value) {
        return new JAXBElement<String>(_OrigSTAN_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "TxnCt")
    public JAXBElement<String> createTxnCt(String value) {
        return new JAXBElement<String>(_TxnCt_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchantID")
    public JAXBElement<String> createMerchantID(String value) {
        return new JAXBElement<String>(_MerchantID_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MrktSpecificDataInd")
    public JAXBElement<MrktSpecificDataIndType> createMrktSpecificDataInd(
            MrktSpecificDataIndType value) {
        return new JAXBElement<MrktSpecificDataIndType>(_MrktSpecificDataInd_QNAME,
                MrktSpecificDataIndType.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "CardActivDate")
    public JAXBElement<String> createCardActivDate(String value) {
        return new JAXBElement<String>(_CardActivDate_QNAME, String.class, null, value);
    }

    @XmlElementDecl(namespace = "com/firstdata/Merchant/gmfV2.08", name = "MerchID")
    public JAXBElement<String> createMerchID(String value) {
        return new JAXBElement<String>(_MerchID_QNAME, String.class, null, value);
    }

}
