//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OfferGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfferGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}POSOfferCap" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferDesc" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferResInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferRespReasCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferProvName" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferAmount" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ReceiptCopy" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}VarCustRctTxt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferProvID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferPubID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OfferPubName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfferGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "posOfferCap",
    "offerDesc",
    "offerResInd",
    "offerRespReasCode",
    "offerID",
    "offerProvName",
    "offerAmount",
    "receiptCopy",
    "varCustRctTxt",
    "offerProvID",
    "offerPubID",
    "offerPubName"
})
public class OfferGrp {

    @XmlElement(name = "POSOfferCap")
    protected String posOfferCap;
    @XmlElement(name = "OfferDesc")
    protected String offerDesc;
    @XmlElement(name = "OfferResInd")
    protected String offerResInd;
    @XmlElement(name = "OfferRespReasCode")
    protected String offerRespReasCode;
    @XmlElement(name = "OfferID")
    protected String offerID;
    @XmlElement(name = "OfferProvName")
    protected String offerProvName;
    @XmlElement(name = "OfferAmount")
    protected String offerAmount;
    @XmlElement(name = "ReceiptCopy")
    protected String receiptCopy;
    @XmlElement(name = "VarCustRctTxt")
    protected String varCustRctTxt;
    @XmlElement(name = "OfferProvID")
    protected String offerProvID;
    @XmlElement(name = "OfferPubID")
    protected String offerPubID;
    @XmlElement(name = "OfferPubName")
    protected String offerPubName;

    /**
     * Gets the value of the posOfferCap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSOfferCap() {
        return posOfferCap;
    }

    /**
     * Sets the value of the posOfferCap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSOfferCap(String value) {
        this.posOfferCap = value;
    }

    /**
     * Gets the value of the offerDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferDesc() {
        return offerDesc;
    }

    /**
     * Sets the value of the offerDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferDesc(String value) {
        this.offerDesc = value;
    }

    /**
     * Gets the value of the offerResInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferResInd() {
        return offerResInd;
    }

    /**
     * Sets the value of the offerResInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferResInd(String value) {
        this.offerResInd = value;
    }

    /**
     * Gets the value of the offerRespReasCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferRespReasCode() {
        return offerRespReasCode;
    }

    /**
     * Sets the value of the offerRespReasCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferRespReasCode(String value) {
        this.offerRespReasCode = value;
    }

    /**
     * Gets the value of the offerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferID() {
        return offerID;
    }

    /**
     * Sets the value of the offerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferID(String value) {
        this.offerID = value;
    }

    /**
     * Gets the value of the offerProvName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferProvName() {
        return offerProvName;
    }

    /**
     * Sets the value of the offerProvName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferProvName(String value) {
        this.offerProvName = value;
    }

    /**
     * Gets the value of the offerAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferAmount() {
        return offerAmount;
    }

    /**
     * Sets the value of the offerAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferAmount(String value) {
        this.offerAmount = value;
    }

    /**
     * Gets the value of the receiptCopy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReceiptCopy() {
        return receiptCopy;
    }

    /**
     * Sets the value of the receiptCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReceiptCopy(String value) {
        this.receiptCopy = value;
    }

    /**
     * Gets the value of the varCustRctTxt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarCustRctTxt() {
        return varCustRctTxt;
    }

    /**
     * Sets the value of the varCustRctTxt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarCustRctTxt(String value) {
        this.varCustRctTxt = value;
    }

    /**
     * Gets the value of the offerProvID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferProvID() {
        return offerProvID;
    }

    /**
     * Sets the value of the offerProvID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferProvID(String value) {
        this.offerProvID = value;
    }

    /**
     * Gets the value of the offerPubID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferPubID() {
        return offerPubID;
    }

    /**
     * Sets the value of the offerPubID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferPubID(String value) {
        this.offerPubID = value;
    }

    /**
     * Gets the value of the offerPubName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferPubName() {
        return offerPubName;
    }

    /**
     * Sets the value of the offerPubName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferPubName(String value) {
        this.offerPubName = value;
    }

}
