//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OrderGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OrderDate" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OrderTime" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}DelvryTypeInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShipFirstName" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShipLastName" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingAddr" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingAddr2" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingCity" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingState" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingCtry" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingContactNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingCarrier" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShippingMthd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}OrderRefnum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}SKU" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "orderDate",
    "orderTime",
    "delvryTypeInd",
    "shipFirstName",
    "shipLastName",
    "shippingAddr",
    "shippingAddr2",
    "shippingCity",
    "shippingState",
    "shippingPostalCode",
    "shippingCtry",
    "shippingContactNum",
    "shippingCarrier",
    "shippingMthd",
    "orderRefnum",
    "sku"
})
public class OrderGrp {

    @XmlElement(name = "OrderDate")
    protected String orderDate;
    @XmlElement(name = "OrderTime")
    protected String orderTime;
    @XmlElement(name = "DelvryTypeInd")
    protected String delvryTypeInd;
    @XmlElement(name = "ShipFirstName")
    protected String shipFirstName;
    @XmlElement(name = "ShipLastName")
    protected String shipLastName;
    @XmlElement(name = "ShippingAddr")
    protected String shippingAddr;
    @XmlElement(name = "ShippingAddr2")
    protected String shippingAddr2;
    @XmlElement(name = "ShippingCity")
    protected String shippingCity;
    @XmlElement(name = "ShippingState")
    protected String shippingState;
    @XmlElement(name = "ShippingPostalCode")
    protected String shippingPostalCode;
    @XmlElement(name = "ShippingCtry")
    protected String shippingCtry;
    @XmlElement(name = "ShippingContactNum")
    protected String shippingContactNum;
    @XmlElement(name = "ShippingCarrier")
    protected ShippingCarrierType shippingCarrier;
    @XmlElement(name = "ShippingMthd")
    protected ShippingMthdType shippingMthd;
    @XmlElement(name = "OrderRefnum")
    protected String orderRefnum;
    @XmlElement(name = "SKU")
    protected String sku;

    /**
     * Gets the value of the orderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderDate() {
        return orderDate;
    }

    /**
     * Sets the value of the orderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderDate(String value) {
        this.orderDate = value;
    }

    /**
     * Gets the value of the orderTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderTime() {
        return orderTime;
    }

    /**
     * Sets the value of the orderTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderTime(String value) {
        this.orderTime = value;
    }

    /**
     * Gets the value of the delvryTypeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDelvryTypeInd() {
        return delvryTypeInd;
    }

    /**
     * Sets the value of the delvryTypeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelvryTypeInd(String value) {
        this.delvryTypeInd = value;
    }

    /**
     * Gets the value of the shipFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipFirstName() {
        return shipFirstName;
    }

    /**
     * Sets the value of the shipFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipFirstName(String value) {
        this.shipFirstName = value;
    }

    /**
     * Gets the value of the shipLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipLastName() {
        return shipLastName;
    }

    /**
     * Sets the value of the shipLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipLastName(String value) {
        this.shipLastName = value;
    }

    /**
     * Gets the value of the shippingAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingAddr() {
        return shippingAddr;
    }

    /**
     * Sets the value of the shippingAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingAddr(String value) {
        this.shippingAddr = value;
    }

    /**
     * Gets the value of the shippingAddr2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingAddr2() {
        return shippingAddr2;
    }

    /**
     * Sets the value of the shippingAddr2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingAddr2(String value) {
        this.shippingAddr2 = value;
    }

    /**
     * Gets the value of the shippingCity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingCity() {
        return shippingCity;
    }

    /**
     * Sets the value of the shippingCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingCity(String value) {
        this.shippingCity = value;
    }

    /**
     * Gets the value of the shippingState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingState() {
        return shippingState;
    }

    /**
     * Sets the value of the shippingState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingState(String value) {
        this.shippingState = value;
    }

    /**
     * Gets the value of the shippingPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingPostalCode() {
        return shippingPostalCode;
    }

    /**
     * Sets the value of the shippingPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingPostalCode(String value) {
        this.shippingPostalCode = value;
    }

    /**
     * Gets the value of the shippingCtry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingCtry() {
        return shippingCtry;
    }

    /**
     * Sets the value of the shippingCtry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingCtry(String value) {
        this.shippingCtry = value;
    }

    /**
     * Gets the value of the shippingContactNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingContactNum() {
        return shippingContactNum;
    }

    /**
     * Sets the value of the shippingContactNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingContactNum(String value) {
        this.shippingContactNum = value;
    }

    /**
     * Gets the value of the shippingCarrier property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingCarrierType }
     *     
     */
    public ShippingCarrierType getShippingCarrier() {
        return shippingCarrier;
    }

    /**
     * Sets the value of the shippingCarrier property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingCarrierType }
     *     
     */
    public void setShippingCarrier(ShippingCarrierType value) {
        this.shippingCarrier = value;
    }

    /**
     * Gets the value of the shippingMthd property.
     * 
     * @return
     *     possible object is
     *     {@link ShippingMthdType }
     *     
     */
    public ShippingMthdType getShippingMthd() {
        return shippingMthd;
    }

    /**
     * Sets the value of the shippingMthd property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShippingMthdType }
     *     
     */
    public void setShippingMthd(ShippingMthdType value) {
        this.shippingMthd = value;
    }

    /**
     * Gets the value of the orderRefnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderRefnum() {
        return orderRefnum;
    }

    /**
     * Sets the value of the orderRefnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderRefnum(String value) {
        this.orderRefnum = value;
    }

    /**
     * Gets the value of the sku property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSKU() {
        return sku;
    }

    /**
     * Sets the value of the sku property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSKU(String value) {
        this.sku = value;
    }

}
