/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrigAuthGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = {
        "origAuthID", "origLocalDateTime", "origTranDateTime", "origSTAN", "origRespCode" })
public class OrigAuthGrp {

    @XmlElement(name = "OrigAuthID", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String origAuthID;
    @XmlElement(name = "OrigLocalDateTime", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String origLocalDateTime;
    @XmlElement(name = "OrigTranDateTime", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String origTranDateTime;
    @XmlElement(name = "OrigSTAN", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String origSTAN;
    @XmlElement(name = "OrigRespCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String origRespCode;

    public String getOrigAuthID() {
        return origAuthID;
    }

    public void setOrigAuthID(String value) {
        this.origAuthID = value;
    }

    public String getOrigLocalDateTime() {
        return origLocalDateTime;
    }

    public void setOrigLocalDateTime(String value) {
        this.origLocalDateTime = value;
    }

    public String getOrigTranDateTime() {
        return origTranDateTime;
    }

    public void setOrigTranDateTime(String value) {
        this.origTranDateTime = value;
    }

    public String getOrigSTAN() {
        return origSTAN;
    }

    public void setOrigSTAN(String value) {
        this.origSTAN = value;
    }

    public String getOrigRespCode() {
        return origRespCode;
    }

    public void setOrigRespCode(String value) {
        this.origRespCode = value;
    }

}
