/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PinlessDebitRequestDetails", namespace = "com/firstdata/Merchant/gmfV2.08",
        propOrder = { "commonGrp", "billPayGrp", "altMerchNameAndAddrGrp", "cardGrp", "taGrp",
                "offerGrp", "ecommGrp", "visaGrp", "debitGrp" })
public class PinlessDebitRequestDetails {

    @XmlElement(name = "CommonGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CommonGrp commonGrp;
    @XmlElement(name = "BillPayGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected BillPayGrp billPayGrp;
    @XmlElement(name = "AltMerchNameAndAddrGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected AltMerchNameAndAddrGrp altMerchNameAndAddrGrp;
    @XmlElement(name = "CardGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected CardGrp cardGrp;
    @XmlElement(name = "TAGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected TAGrp taGrp;
    @XmlElement(name = "OfferGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected OfferGrp offerGrp;
    @XmlElement(name = "EcommGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected EcommGrp ecommGrp;
    @XmlElement(name = "VisaGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected VisaGrp visaGrp;
    @XmlElement(name = "DebitGrp", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected DebitGrp debitGrp;

    public CommonGrp getCommonGrp() {
        return commonGrp;
    }

    public void setCommonGrp(CommonGrp value) {
        this.commonGrp = value;
    }

    public BillPayGrp getBillPayGrp() {
        return billPayGrp;
    }

    public void setBillPayGrp(BillPayGrp value) {
        this.billPayGrp = value;
    }

    public AltMerchNameAndAddrGrp getAltMerchNameAndAddrGrp() {
        return altMerchNameAndAddrGrp;
    }

    public void setAltMerchNameAndAddrGrp(AltMerchNameAndAddrGrp value) {
        this.altMerchNameAndAddrGrp = value;
    }

    public CardGrp getCardGrp() {
        return cardGrp;
    }

    public void setCardGrp(CardGrp value) {
        this.cardGrp = value;
    }

    public TAGrp getTAGrp() {
        return taGrp;
    }

    public void setTAGrp(TAGrp value) {
        this.taGrp = value;
    }

    public OfferGrp getOfferGrp() {
        return offerGrp;
    }

    public void setOfferGrp(OfferGrp value) {
        this.offerGrp = value;
    }

    public EcommGrp getEcommGrp() {
        return ecommGrp;
    }

    public void setEcommGrp(EcommGrp value) {
        this.ecommGrp = value;
    }

    public VisaGrp getVisaGrp() {
        return visaGrp;
    }

    public void setVisaGrp(VisaGrp value) {
        this.visaGrp = value;
    }

    public DebitGrp getDebitGrp() {
        return debitGrp;
    }

    public void setDebitGrp(DebitGrp value) {
        this.debitGrp = value;
    }

}
