//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PurchCardlvl2Grp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PurchCardlvl2Grp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TaxAmt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}TaxInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}PurchIdfr" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}PCOrderNum" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}DiscntAmt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}FrghtAmt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}DutyAmt" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}DestPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ShipFromPostalCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}DestCtryCode" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}MerchTaxID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}ProdDesc" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchCardlvl2Grp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "taxAmt",
    "taxInd",
    "purchIdfr",
    "pcOrderNum",
    "discntAmt",
    "frghtAmt",
    "dutyAmt",
    "destPostalCode",
    "shipFromPostalCode",
    "destCtryCode",
    "merchTaxID",
    "prodDesc"
})
public class PurchCardlvl2Grp {

    @XmlElement(name = "TaxAmt")
    protected String taxAmt;
    @XmlElement(name = "TaxInd")
    protected String taxInd;
    @XmlElement(name = "PurchIdfr")
    protected String purchIdfr;
    @XmlElement(name = "PCOrderNum")
    protected String pcOrderNum;
    @XmlElement(name = "DiscntAmt")
    protected String discntAmt;
    @XmlElement(name = "FrghtAmt")
    protected String frghtAmt;
    @XmlElement(name = "DutyAmt")
    protected String dutyAmt;
    @XmlElement(name = "DestPostalCode")
    protected String destPostalCode;
    @XmlElement(name = "ShipFromPostalCode")
    protected String shipFromPostalCode;
    @XmlElement(name = "DestCtryCode")
    protected String destCtryCode;
    @XmlElement(name = "MerchTaxID")
    protected String merchTaxID;
    @XmlElement(name = "ProdDesc")
    protected String prodDesc;

    /**
     * Gets the value of the taxAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxAmt() {
        return taxAmt;
    }

    /**
     * Sets the value of the taxAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxAmt(String value) {
        this.taxAmt = value;
    }

    /**
     * Gets the value of the taxInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxInd() {
        return taxInd;
    }

    /**
     * Sets the value of the taxInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxInd(String value) {
        this.taxInd = value;
    }

    /**
     * Gets the value of the purchIdfr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchIdfr() {
        return purchIdfr;
    }

    /**
     * Sets the value of the purchIdfr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchIdfr(String value) {
        this.purchIdfr = value;
    }

    /**
     * Gets the value of the pcOrderNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCOrderNum() {
        return pcOrderNum;
    }

    /**
     * Sets the value of the pcOrderNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCOrderNum(String value) {
        this.pcOrderNum = value;
    }

    /**
     * Gets the value of the discntAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDiscntAmt() {
        return discntAmt;
    }

    /**
     * Sets the value of the discntAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiscntAmt(String value) {
        this.discntAmt = value;
    }

    /**
     * Gets the value of the frghtAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrghtAmt() {
        return frghtAmt;
    }

    /**
     * Sets the value of the frghtAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrghtAmt(String value) {
        this.frghtAmt = value;
    }

    /**
     * Gets the value of the dutyAmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDutyAmt() {
        return dutyAmt;
    }

    /**
     * Sets the value of the dutyAmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDutyAmt(String value) {
        this.dutyAmt = value;
    }

    /**
     * Gets the value of the destPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestPostalCode() {
        return destPostalCode;
    }

    /**
     * Sets the value of the destPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestPostalCode(String value) {
        this.destPostalCode = value;
    }

    /**
     * Gets the value of the shipFromPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipFromPostalCode() {
        return shipFromPostalCode;
    }

    /**
     * Sets the value of the shipFromPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipFromPostalCode(String value) {
        this.shipFromPostalCode = value;
    }

    /**
     * Gets the value of the destCtryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestCtryCode() {
        return destCtryCode;
    }

    /**
     * Sets the value of the destCtryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestCtryCode(String value) {
        this.destCtryCode = value;
    }

    /**
     * Gets the value of the merchTaxID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerchTaxID() {
        return merchTaxID;
    }

    /**
     * Sets the value of the merchTaxID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerchTaxID(String value) {
        this.merchTaxID = value;
    }

    /**
     * Gets the value of the prodDesc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProdDesc() {
        return prodDesc;
    }

    /**
     * Sets the value of the prodDesc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProdDesc(String value) {
        this.prodDesc = value;
    }

}
