/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PurchCardlvl2Grp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = {
        "taxAmt", "taxInd", "purchIdfr", "pcOrderNum", "discntAmt", "frghtAmt", "dutyAmt",
        "destPostalCode", "shipFromPostalCode", "destCtryCode", "merchTaxID", "prodDesc" })
public class PurchCardlvl2Grp {

    @XmlElement(name = "TaxAmt", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String taxAmt;
    @XmlElement(name = "TaxInd", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String taxInd;
    @XmlElement(name = "PurchIdfr", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String purchIdfr;
    @XmlElement(name = "PCOrderNum", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String pcOrderNum;
    @XmlElement(name = "DiscntAmt", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String discntAmt;
    @XmlElement(name = "FrghtAmt", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String frghtAmt;
    @XmlElement(name = "DutyAmt", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String dutyAmt;
    @XmlElement(name = "DestPostalCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String destPostalCode;
    @XmlElement(name = "ShipFromPostalCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String shipFromPostalCode;
    @XmlElement(name = "DestCtryCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String destCtryCode;
    @XmlElement(name = "MerchTaxID", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String merchTaxID;
    @XmlElement(name = "ProdDesc", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected List<String> prodDesc;

    public String getTaxAmt() {
        return taxAmt;
    }

    public void setTaxAmt(String value) {
        this.taxAmt = value;
    }

    public String getTaxInd() {
        return taxInd;
    }

    public void setTaxInd(String value) {
        this.taxInd = value;
    }

    public String getPurchIdfr() {
        return purchIdfr;
    }

    public void setPurchIdfr(String value) {
        this.purchIdfr = value;
    }

    public String getPCOrderNum() {
        return pcOrderNum;
    }

    public void setPCOrderNum(String value) {
        this.pcOrderNum = value;
    }

    public String getDiscntAmt() {
        return discntAmt;
    }

    public void setDiscntAmt(String value) {
        this.discntAmt = value;
    }

    public String getFrghtAmt() {
        return frghtAmt;
    }

    public void setFrghtAmt(String value) {
        this.frghtAmt = value;
    }

    public String getDutyAmt() {
        return dutyAmt;
    }

    public void setDutyAmt(String value) {
        this.dutyAmt = value;
    }

    public String getDestPostalCode() {
        return destPostalCode;
    }

    public void setDestPostalCode(String value) {
        this.destPostalCode = value;
    }

    public String getShipFromPostalCode() {
        return shipFromPostalCode;
    }

    public void setShipFromPostalCode(String value) {
        this.shipFromPostalCode = value;
    }

    public String getDestCtryCode() {
        return destCtryCode;
    }

    public void setDestCtryCode(String value) {
        this.destCtryCode = value;
    }

    public String getMerchTaxID() {
        return merchTaxID;
    }

    public void setMerchTaxID(String value) {
        this.merchTaxID = value;
    }

    public List<String> getProdDesc() {
        if (prodDesc == null) {
            prodDesc = new ArrayList<String>();
        }
        return this.prodDesc;
    }

}
