/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = { "respCode",
        "authID", "addtlRespData", "sttlmDate", "athNtwkID", "errorData" })
public class RespGrp {

    @XmlElement(name = "RespCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String respCode;
    @XmlElement(name = "AuthID", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String authID;
    @XmlElement(name = "AddtlRespData", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String addtlRespData;
    @XmlElement(name = "SttlmDate", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String sttlmDate;
    @XmlElement(name = "AthNtwkID", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String athNtwkID;
    @XmlElement(name = "ErrorData", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String errorData;

    public String getRespCode() {
        return respCode;
    }

    public void setRespCode(String value) {
        this.respCode = value;
    }

    public String getAuthID() {
        return authID;
    }

    public void setAuthID(String value) {
        this.authID = value;
    }

    public String getAddtlRespData() {
        return addtlRespData;
    }

    public void setAddtlRespData(String value) {
        this.addtlRespData = value;
    }

    public String getSttlmDate() {
        return sttlmDate;
    }

    public void setSttlmDate(String value) {
        this.sttlmDate = value;
    }

    public String getAthNtwkID() {
        return athNtwkID;
    }

    public void setAthNtwkID(String value) {
        this.athNtwkID = value;
    }

    public String getErrorData() {
        return errorData;
    }

    public void setErrorData(String value) {
        this.errorData = value;
    }

}
