/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlType(name = "ReversalIndType", namespace = "com/firstdata/Merchant/gmfV2.08")
@XmlEnum
public enum ReversalIndType {

    @XmlEnumValue("Timeout")
    TIMEOUT("Timeout"), @XmlEnumValue("Void")
    VOID("Void"), @XmlEnumValue("VoidFr")
    VOID_FR("VoidFr"), @XmlEnumValue("TORVoid")
    TOR_VOID("TORVoid"), @XmlEnumValue("Partial")
    PARTIAL("Partial");
    private final String value;

    ReversalIndType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReversalIndType fromValue(String v) {
        for (ReversalIndType c : ReversalIndType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
