//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 02:31:56 PM EST 
//


package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecrTxnGrp complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecrTxnGrp">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}MerchTxnID" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}UCAFCollectInd" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}SecrTxnAD" minOccurs="0"/>
 *         &lt;element ref="{com/firstdata/Merchant/gmfV1.1}CAVVResultCode" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecrTxnGrp", namespace = "com/firstdata/Merchant/gmfV1.1", propOrder = {
    "merchTxnID",
    "ucafCollectInd",
    "secrTxnAD",
    "cavvResultCode"
})
public class SecrTxnGrp {

    @XmlElement(name = "MerchTxnID")
    protected byte[] merchTxnID;
    @XmlElement(name = "UCAFCollectInd")
    protected String ucafCollectInd;
    @XmlElement(name = "SecrTxnAD")
    protected byte[] secrTxnAD;
    @XmlElement(name = "CAVVResultCode")
    protected String cavvResultCode;

    /**
     * Gets the value of the merchTxnID property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getMerchTxnID() {
        return merchTxnID;
    }

    /**
     * Sets the value of the merchTxnID property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setMerchTxnID(byte[] value) {
        this.merchTxnID = ((byte[]) value);
    }

    /**
     * Gets the value of the ucafCollectInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUCAFCollectInd() {
        return ucafCollectInd;
    }

    /**
     * Sets the value of the ucafCollectInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUCAFCollectInd(String value) {
        this.ucafCollectInd = value;
    }

    /**
     * Gets the value of the secrTxnAD property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getSecrTxnAD() {
        return secrTxnAD;
    }

    /**
     * Sets the value of the secrTxnAD property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setSecrTxnAD(byte[] value) {
        this.secrTxnAD = ((byte[]) value);
    }

    /**
     * Gets the value of the cavvResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAVVResultCode() {
        return cavvResultCode;
    }

    /**
     * Sets the value of the cavvResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAVVResultCode(String value) {
        this.cavvResultCode = value;
    }

}
