/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StoredValueGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = {
        "eschtblTxn", "cardClass", "cardCost", "faCode" })
public class StoredValueGrp {

    @XmlElement(name = "EschtblTxn", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected EschtblTxnType eschtblTxn;
    @XmlElement(name = "CardClass", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String cardClass;
    @XmlElement(name = "CardCost", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String cardCost;
    @XmlElement(name = "FACode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String faCode;

    public EschtblTxnType getEschtblTxn() {
        return eschtblTxn;
    }

    public void setEschtblTxn(EschtblTxnType value) {
        this.eschtblTxn = value;
    }

    public String getCardClass() {
        return cardClass;
    }

    public void setCardClass(String value) {
        this.cardClass = value;
    }

    public String getCardCost() {
        return cardCost;
    }

    public void setCardCost(String value) {
        this.cardCost = value;
    }

    public String getFACode() {
        return faCode;
    }

    public void setFACode(String value) {
        this.faCode = value;
    }

}
