/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TAGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = { "sctyLvl",
        "encrptType", "encrptTrgt", "keyID", "encrptBlock", "tknType", "tkn", "sctyKeyUpdInd",
        "taSctyKey", "taExpDate" })
public class TAGrp {

    @XmlElement(name = "SctyLvl", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected SctyLvlType sctyLvl;
    @XmlElement(name = "EncrptType", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected EncrptTypeType encrptType;
    @XmlElement(name = "EncrptTrgt", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected EncrptTrgtType encrptTrgt;
    @XmlElement(name = "KeyID", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String keyID;
    @XmlElement(name = "EncrptBlock", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String encrptBlock;
    @XmlElement(name = "TknType", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String tknType;
    @XmlElement(name = "Tkn", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String tkn;
    @XmlElement(name = "SctyKeyUpdInd", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String sctyKeyUpdInd;
    @XmlElement(name = "TASctyKey", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String taSctyKey;
    @XmlElement(name = "TAExpDate", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String taExpDate;

    public SctyLvlType getSctyLvl() {
        return sctyLvl;
    }

    public void setSctyLvl(SctyLvlType value) {
        this.sctyLvl = value;
    }

    public EncrptTypeType getEncrptType() {
        return encrptType;
    }

    public void setEncrptType(EncrptTypeType value) {
        this.encrptType = value;
    }

    public EncrptTrgtType getEncrptTrgt() {
        return encrptTrgt;
    }

    public void setEncrptTrgt(EncrptTrgtType value) {
        this.encrptTrgt = value;
    }

    public String getKeyID() {
        return keyID;
    }

    public void setKeyID(String value) {
        this.keyID = value;
    }

    public String getEncrptBlock() {
        return encrptBlock;
    }

    public void setEncrptBlock(String value) {
        this.encrptBlock = value;
    }

    public String getTknType() {
        return tknType;
    }

    public void setTknType(String value) {
        this.tknType = value;
    }

    public String getTkn() {
        return tkn;
    }

    public void setTkn(String value) {
        this.tkn = value;
    }

    public String getSctyKeyUpdInd() {
        return sctyKeyUpdInd;
    }

    public void setSctyKeyUpdInd(String value) {
        this.sctyKeyUpdInd = value;
    }

    public String getTASctyKey() {
        return taSctyKey;
    }

    public void setTASctyKey(String value) {
        this.taSctyKey = value;
    }

    public String getTAExpDate() {
        return taExpDate;
    }

    public void setTAExpDate(String value) {
        this.taExpDate = value;
    }

}
