/*
 * SnapLogic - Data Integration
 *
 * Copyright (C) 2014, SnapLogic, Inc. All rights reserved.
 *
 * This program is licensed under the terms of
 * the SnapLogic Commercial Subscription agreement.
 *
 * "SnapLogic" is a trademark of SnapLogic, Inc.
 */
package com.snaplogic.snaps.firstdata.gmf.proxy;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
 * Implementation. Any modifications to this file will be lost upon recompilation of the source
 * schema.
 * 
 * @author svatada
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VisaGrp", namespace = "com/firstdata/Merchant/gmfV2.08", propOrder = { "aci",
        "mrktSpecificDataInd", "existingDebtInd", "cardLevelResult", "sourceReasonCode", "transID",
        "visaBID", "visaAUAR", "taxAmtCapablt" })
public class VisaGrp {

    @XmlElement(name = "ACI", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected ACIType aci;
    @XmlElement(name = "MrktSpecificDataInd", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected MrktSpecificDataIndType mrktSpecificDataInd;
    @XmlElement(name = "ExistingDebtInd", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String existingDebtInd;
    @XmlElement(name = "CardLevelResult", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String cardLevelResult;
    @XmlElement(name = "SourceReasonCode", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String sourceReasonCode;
    @XmlElement(name = "TransID", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String transID;
    @XmlElement(name = "VisaBID", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected List<String> visaBID;
    @XmlElement(name = "VisaAUAR", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected List<String> visaAUAR;
    @XmlElement(name = "TaxAmtCapablt", namespace = "com/firstdata/Merchant/gmfV2.08")
    protected String taxAmtCapablt;

    public ACIType getACI() {
        return aci;
    }

    public void setACI(ACIType value) {
        this.aci = value;
    }

    public MrktSpecificDataIndType getMrktSpecificDataInd() {
        return mrktSpecificDataInd;
    }

    public void setMrktSpecificDataInd(MrktSpecificDataIndType value) {
        this.mrktSpecificDataInd = value;
    }

    public String getExistingDebtInd() {
        return existingDebtInd;
    }

    public void setExistingDebtInd(String value) {
        this.existingDebtInd = value;
    }

    public String getCardLevelResult() {
        return cardLevelResult;
    }

    public void setCardLevelResult(String value) {
        this.cardLevelResult = value;
    }

    public String getSourceReasonCode() {
        return sourceReasonCode;
    }

    public void setSourceReasonCode(String value) {
        this.sourceReasonCode = value;
    }

    public String getTransID() {
        return transID;
    }

    public void setTransID(String value) {
        this.transID = value;
    }

    public List<String> getVisaBID() {
        if (visaBID == null) {
            visaBID = new ArrayList<String>();
        }
        return this.visaBID;
    }

    public List<String> getVisaAUAR() {
        if (visaAUAR == null) {
            visaAUAR = new ArrayList<String>();
        }
        return this.visaAUAR;
    }

    public String getTaxAmtCapablt() {
        return taxAmtCapablt;
    }

    public void setTaxAmtCapablt(String value) {
        this.taxAmtCapablt = value;
    }

}
