//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//


package com.snaplogic.snaps.firstdata.dw.rcservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

@WebServiceClient(name = "rcService", targetNamespace = "http://securetransport.dw/rcservice/soap", wsdlLocation = "META-INF/wsdl/rcservice.wsdl")
public class RcService
    extends Service
{

    private final static URL RCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.snaplogic.snaps.firstdata.dw.rcservice.RcService.class.getName());

    static {
        URL url = null;
        try {
            url = com.snaplogic.snaps.firstdata.dw.rcservice.RcService.class.getResource("/META-INF/wsdl/rcservice.wsdl");
            if (url == null) throw new MalformedURLException("/META-INF/wsdl/rcservice.wsdl does not exist in the module.");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'META-INF/wsdl/rcservice.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RCSERVICE_WSDL_LOCATION = url;
    }

    public RcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RcService() {
        super(RCSERVICE_WSDL_LOCATION, new QName("http://securetransport.dw/rcservice/soap", "rcService"));
    }

    /**
     * 
     * @return
     *     returns RcPortType
     */
    @WebEndpoint(name = "rcServicePort")
    public RcPortType getRcServicePort() {
        return super.getPort(new QName("http://securetransport.dw/rcservice/soap", "rcServicePort"), RcPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RcPortType
     */
    @WebEndpoint(name = "rcServicePort")
    public RcPortType getRcServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://securetransport.dw/rcservice/soap", "rcServicePort"), RcPortType.class, features);
    }

}
